import React,{useMemo,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {BusFront,Factory} from 'lucide-react';
import './clientPortal.css';
import {ClientPortalProvider} from './ClientPortalContext'; import ClientPortalShell from './components/ClientPortalShell'; import DashboardPage from './pages/DashboardPage'; import SitesPage from './pages/SitesPage'; import UsersPage from './pages/UsersPage'; import VehiclesPage from './pages/VehiclesPage'; import DriversPage from './pages/DriversPage'; import PartiesPage from './pages/PartiesPage'; import ReportsPage from './pages/ReportsPage'; import TravelsPage from './pages/TravelsPage'; import CementPage from './pages/CementPage'; import FinancePage from './pages/FinancePage'; import SettingsPage from './pages/SettingsPage'; import ProfileSecurityPage from './pages/ProfileSecurityPage'; import ComingSoonPage from './pages/ComingSoonPage';
import {getDemoCompany} from './data/demoData'; import {getFleetPack} from './config/fleetPacks'; import {defaultPermissionSet,getModuleByRoute} from './config/moduleCatalog';

function page(route){if(route==='dashboard')return <DashboardPage/>;if(route==='sites')return <SitesPage/>;if(route==='users')return <UsersPage/>;if(route==='vehicles')return <VehiclesPage/>;if(route==='drivers')return <DriversPage/>;if(route==='parties')return <PartiesPage/>;if(route==='reports')return <ReportsPage/>;if(route==='finance'||route==='expenses')return <FinancePage/>;if(route==='settings')return <SettingsPage/>;if(route==='profile-security')return <ProfileSecurityPage/>;if(route.startsWith('travels/'))return <TravelsPage section={route.split('/')[1]}/>;if(route.startsWith('cement/'))return <CementPage section={route.split('/')[1]}/>;const m=getModuleByRoute(route);return <ComingSoonPage title={m?.label||'Module'}/>}
function access(packKey){const keys=getFleetPack(packKey)?.recommendedModules||[];return {allSites:true,siteIds:[],moduleKeys:keys,companyModuleKeys:keys,modulePermissions:Object.fromEntries(keys.map(k=>[k,defaultPermissionSet(true)]))};}

export default function DemoPortalApp(){const location=useLocation();const parts=location.pathname.split('/').filter(Boolean);const mode=parts[1];if(!['travels','cement'].includes(mode))return <div className="bf-demo-home"><div className="bf-demo-picker"><div className="bf-brand" style={{padding:0,border:0,color:'#2d174d',marginBottom:20}}><div className="bf-brand-mark" style={{color:'#fff'}}>BF</div><div><strong>Buddy Fleets Demo</strong><small style={{color:'#777'}}>portal.buddyfleets.in/demo</small></div></div><h1>Choose a fleet demo</h1><p>Both demos use the same Client Portal engine. Only fleet pack, modules, dashboard widgets and sample data change.</p><div className="bf-grid bf-grid-2"><Link to="/demo/travels/dashboard" className="bf-card bf-demo-option" style={{textDecoration:'none',color:'inherit'}}><BusFront size={34} color="#7a00ff"/><h3>Small Travels</h3><p>Bookings, vehicle availability, driver allocation, trip sheets, expenses, billing and reports.</p><span className="bf-btn bf-btn-primary">Explore Travels Demo</span></Link><Link to="/demo/cement/dashboard" className="bf-card bf-demo-option" style={{textDecoration:'none',color:'inherit'}}><Factory size={34} color="#7a00ff"/><h3>Bagged Cement</h3><p>Multi-plant placement, queue, loading, tonnage, dispatch, dealer delivery, POD, TAT and reports.</p><span className="bf-btn bf-btn-primary">Explore Cement Demo</span></Link></div></div></div>;
 const packKey=mode==='cement'?'bagged_cement':'travels'; const [demoData,setDemoData]=useState(()=>getDemoCompany(mode));const basePath=`/demo/${mode}`;const route=location.pathname.replace(basePath,'').replace(/^\/+|\/+$/g,'')||'dashboard';const mutateDemo=(key,fn)=>setDemoData(d=>({...d,[key]:fn(d[key]||[])}));const value=useMemo(()=>({company:demoData.company,currentUser:demoData.currentUser,settings:{fleet_pack:packKey},sites:demoData.sites,userAccess:access(packKey),data:demoData,demo:true,demoMode:mode,basePath,onLogout:()=>{},refresh:async()=>{},apiAction:async()=>({ok:true}),mutateDemo}),[demoData,basePath,mode,packKey]);return <ClientPortalProvider value={value}><ClientPortalShell>{page(route)}</ClientPortalShell></ClientPortalProvider>}
