$ErrorActionPreference = 'Stop'

function Read-Utf8NoBom([string]$Path) {
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::ReadAllText($Path, $enc)
}

function Write-Utf8NoBom([string]$Path, [string]$Text) {
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Text, $enc)
}

function Backup-Once([string]$Path) {
    $backup = "$Path.before-session-system.bak"
    if (-not (Test-Path $backup)) {
        Copy-Item $Path $backup -Force
    }
}

$root = (Get-Location).Path
$componentPath = Join-Path $root 'src\components\SessionControl.jsx'
$appPath = Join-Path $root 'src\App.jsx'
$devLayoutPath = Join-Path $root 'src\layouts\DeveloperLayout.jsx'
$portalLayoutPath = Join-Path $root 'src\clientPortal\components\UniversalDashboardShell.jsx'
$sessionApiPath = Join-Path $root 'api\auth\session.js'

foreach ($p in @($appPath,$devLayoutPath,$portalLayoutPath,$sessionApiPath)) {
    if (-not (Test-Path $p)) {
        throw "Required file not found: $p"
    }
}

New-Item -ItemType Directory -Force (Split-Path $componentPath) | Out-Null
$componentBytes = [Convert]::FromBase64String('aW1wb3J0IFJlYWN0LCB7IHVzZUNhbGxiYWNrLCB1c2VFZmZlY3QsIHVzZU1lbW8sIHVzZVJlZiwgdXNlU3RhdGUgfSBmcm9tICdyZWFjdCc7CmltcG9ydCB7IENsb2NrMywgU2hpZWxkQWxlcnQsIFRpbWVyUmVzZXQsIFggfSBmcm9tICdsdWNpZGUtcmVhY3QnOwoKY29uc3QgREVGQVVMVF9NSU5VVEVTID0gMzA7CmNvbnN0IEFMTE9XRURfTUlOVVRFUyA9IFszMCwgNjAsIDkwXTsKY29uc3QgVE9VQ0hfVEhST1RUTEVfTVMgPSAxNTAwMDsKY29uc3QgUlVOVElNRV9LRVkgPSAnYmZfc2Vzc2lvbl9ydW50aW1lX3YyJzsKY29uc3QgQUNUSVZJVFlfS0VZID0gJ2J1ZGR5X2ZsZWV0c19sYXN0X2FjdGl2aXR5JzsKCmZ1bmN0aW9uIHJlYWRSdW50aW1lKCkgewogIHRyeSB7CiAgICBjb25zdCByYXcgPSB3aW5kb3cubG9jYWxTdG9yYWdlLmdldEl0ZW0oUlVOVElNRV9LRVkpOwogICAgaWYgKCFyYXcpIHJldHVybiBudWxsOwogICAgY29uc3QgdmFsdWUgPSBKU09OLnBhcnNlKHJhdyk7CiAgICBpZiAoIXZhbHVlIHx8ICFOdW1iZXIuaXNGaW5pdGUoTnVtYmVyKHZhbHVlLmV4cGlyZXNBdCkpKSByZXR1cm4gbnVsbDsKICAgIGNvbnN0IG1pbnV0ZXMgPSBBTExPV0VEX01JTlVURVMuaW5jbHVkZXMoTnVtYmVyKHZhbHVlLnRpbWVvdXRNaW51dGVzKSkKICAgICAgPyBOdW1iZXIodmFsdWUudGltZW91dE1pbnV0ZXMpCiAgICAgIDogREVGQVVMVF9NSU5VVEVTOwogICAgcmV0dXJuIHsgZXhwaXJlc0F0OiBOdW1iZXIodmFsdWUuZXhwaXJlc0F0KSwgdGltZW91dE1pbnV0ZXM6IG1pbnV0ZXMgfTsKICB9IGNhdGNoIHsKICAgIHJldHVybiBudWxsOwogIH0KfQoKZnVuY3Rpb24gd3JpdGVSdW50aW1lKHJ1bnRpbWUpIHsKICB0cnkgewogICAgd2luZG93LmxvY2FsU3RvcmFnZS5zZXRJdGVtKFJVTlRJTUVfS0VZLCBKU09OLnN0cmluZ2lmeShydW50aW1lKSk7CiAgfSBjYXRjaCB7CiAgICAvLyBVSSBzdGF0ZSBvbmx5LgogIH0KfQoKZnVuY3Rpb24gZm9ybWF0UmVtYWluaW5nKG1zKSB7CiAgY29uc3QgdG90YWwgPSBNYXRoLm1heCgwLCBNYXRoLmNlaWwobXMgLyAxMDAwKSk7CiAgY29uc3QgbWludXRlcyA9IE1hdGguZmxvb3IodG90YWwgLyA2MCk7CiAgY29uc3Qgc2Vjb25kcyA9IHRvdGFsICUgNjA7CiAgcmV0dXJuIGAke1N0cmluZyhtaW51dGVzKS5wYWRTdGFydCgyLCAnMCcpfToke1N0cmluZyhzZWNvbmRzKS5wYWRTdGFydCgyLCAnMCcpfWA7Cn0KCmFzeW5jIGZ1bmN0aW9uIHNlc3Npb25NdXRhdGlvbihhY3Rpb24sIG1pbnV0ZXMpIHsKICBjb25zdCByZXNwb25zZSA9IGF3YWl0IGZldGNoKCcvYXBpL2F1dGgvc2Vzc2lvbicsIHsKICAgIG1ldGhvZDogJ1BPU1QnLAogICAgY3JlZGVudGlhbHM6ICdpbmNsdWRlJywKICAgIGNhY2hlOiAnbm8tc3RvcmUnLAogICAgaGVhZGVyczogewogICAgICBBY2NlcHQ6ICdhcHBsaWNhdGlvbi9qc29uJywKICAgICAgJ0NvbnRlbnQtVHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJywKICAgIH0sCiAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7CiAgICAgIGFjdGlvbiwKICAgICAgdGltZW91dE1pbnV0ZXM6IG1pbnV0ZXMsCiAgICB9KSwKICB9KTsKICBjb25zdCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpLmNhdGNoKCgpID0+ICh7fSkpOwogIHJldHVybiB7IC4uLmRhdGEsIHN0YXR1czogcmVzcG9uc2Uuc3RhdHVzLCBvazogQm9vbGVhbihyZXNwb25zZS5vayAmJiBkYXRhPy5vaykgfTsKfQoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gU2Vzc2lvbkNvbnRyb2woeyBvbkxvZ291dCB9KSB7CiAgY29uc3QgW3J1bnRpbWUsIHNldFJ1bnRpbWVdID0gdXNlU3RhdGUoKCkgPT4gcmVhZFJ1bnRpbWUoKSk7CiAgY29uc3QgW3JlbWFpbmluZywgc2V0UmVtYWluaW5nXSA9IHVzZVN0YXRlKG51bGwpOwogIGNvbnN0IFtvcGVuLCBzZXRPcGVuXSA9IHVzZVN0YXRlKGZhbHNlKTsKICBjb25zdCBbZXhwaXJlZCwgc2V0RXhwaXJlZF0gPSB1c2VTdGF0ZShmYWxzZSk7CiAgY29uc3QgW25vdGljZSwgc2V0Tm90aWNlXSA9IHVzZVN0YXRlKCcnKTsKICBjb25zdCBsYXN0VG91Y2hSZWYgPSB1c2VSZWYoMCk7CiAgY29uc3QgbGFzdExvY2FsQWN0aXZpdHlSZWYgPSB1c2VSZWYoMCk7CiAgY29uc3QgbGFzdENyb3NzVGFiU3luY1JlZiA9IHVzZVJlZigwKTsKICBjb25zdCBleHBpcmVkUmVmID0gdXNlUmVmKGZhbHNlKTsKCiAgY29uc3Qgc3luY0Zyb21TZXJ2ZXIgPSB1c2VDYWxsYmFjayhhc3luYyAoKSA9PiB7CiAgICB0cnkgewogICAgICBjb25zdCByZXNwb25zZSA9IGF3YWl0IGZldGNoKCcvYXBpL2F1dGgvc2Vzc2lvbicsIHsKICAgICAgICBjcmVkZW50aWFsczogJ2luY2x1ZGUnLAogICAgICAgIGNhY2hlOiAnbm8tc3RvcmUnLAogICAgICAgIGhlYWRlcnM6IHsgQWNjZXB0OiAnYXBwbGljYXRpb24vanNvbicgfSwKICAgICAgfSk7CiAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCkuY2F0Y2goKCkgPT4gKHt9KSk7CiAgICAgIGlmICghcmVzcG9uc2Uub2sgfHwgIWRhdGE/Lm9rKSB7CiAgICAgICAgaWYgKFs0MDEsIDQwMywgNDIzXS5pbmNsdWRlcyhyZXNwb25zZS5zdGF0dXMpKSB7CiAgICAgICAgICBzZXRFeHBpcmVkKHRydWUpOwogICAgICAgICAgZXhwaXJlZFJlZi5jdXJyZW50ID0gdHJ1ZTsKICAgICAgICB9CiAgICAgICAgcmV0dXJuOwogICAgICB9CiAgICAgIGNvbnN0IGV4cGlyZXNBdCA9IERhdGUucGFyc2UoZGF0YT8uc2Vzc2lvbj8uZXhwaXJlc0F0IHx8ICcnKTsKICAgICAgaWYgKCFOdW1iZXIuaXNGaW5pdGUoZXhwaXJlc0F0KSkgcmV0dXJuOwogICAgICBjb25zdCB0aW1lb3V0TWludXRlcyA9IEFMTE9XRURfTUlOVVRFUy5pbmNsdWRlcyhOdW1iZXIoZGF0YT8uc2Vzc2lvbj8udGltZW91dE1pbnV0ZXMpKQogICAgICAgID8gTnVtYmVyKGRhdGEuc2Vzc2lvbi50aW1lb3V0TWludXRlcykKICAgICAgICA6IERFRkFVTFRfTUlOVVRFUzsKICAgICAgY29uc3QgbmV4dCA9IHsgZXhwaXJlc0F0LCB0aW1lb3V0TWludXRlcyB9OwogICAgICBzZXRSdW50aW1lKG5leHQpOwogICAgICB3cml0ZVJ1bnRpbWUobmV4dCk7CiAgICAgIHNldEV4cGlyZWQoZmFsc2UpOwogICAgICBleHBpcmVkUmVmLmN1cnJlbnQgPSBmYWxzZTsKICAgIH0gY2F0Y2ggewogICAgICAvLyBUZW1wb3JhcnkgbmV0d29yayBmYWlsdXJlcyBkbyBub3QgZXhwaXJlIHRoZSBVSSBzZXNzaW9uLgogICAgfQogIH0sIFtdKTsKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGxldCBjYW5jZWxsZWQgPSBmYWxzZTsKICAgIGNvbnN0IHJ1biA9IGFzeW5jICgpID0+IHsKICAgICAgaWYgKGNhbmNlbGxlZCkgcmV0dXJuOwogICAgICBhd2FpdCBzeW5jRnJvbVNlcnZlcigpOwogICAgfTsKICAgIHJ1bigpOwogICAgY29uc3QgcG9sbCA9IHdpbmRvdy5zZXRJbnRlcnZhbChydW4sIDYwMDAwKTsKICAgIHJldHVybiAoKSA9PiB7CiAgICAgIGNhbmNlbGxlZCA9IHRydWU7CiAgICAgIHdpbmRvdy5jbGVhckludGVydmFsKHBvbGwpOwogICAgfTsKICB9LCBbc3luY0Zyb21TZXJ2ZXJdKTsKCiAgY29uc3QgdG91Y2ggPSB1c2VDYWxsYmFjayhhc3luYyAoKSA9PiB7CiAgICBpZiAoZXhwaXJlZFJlZi5jdXJyZW50KSByZXR1cm47CiAgICBjb25zdCBub3cgPSBEYXRlLm5vdygpOwogICAgaWYgKG5vdyAtIGxhc3RUb3VjaFJlZi5jdXJyZW50IDwgVE9VQ0hfVEhST1RUTEVfTVMpIHJldHVybjsKICAgIGxhc3RUb3VjaFJlZi5jdXJyZW50ID0gbm93OwoKICAgIGNvbnN0IG1pbnV0ZXMgPSBydW50aW1lPy50aW1lb3V0TWludXRlcyB8fCBERUZBVUxUX01JTlVURVM7CiAgICBjb25zdCByZXN1bHQgPSBhd2FpdCBzZXNzaW9uTXV0YXRpb24oJ1RPVUNIJywgbWludXRlcyk7CiAgICBpZiAocmVzdWx0Lm9rICYmIHJlc3VsdC5leHBpcmVzQXQpIHsKICAgICAgY29uc3QgbmV4dCA9IHsKICAgICAgICBleHBpcmVzQXQ6IERhdGUucGFyc2UocmVzdWx0LmV4cGlyZXNBdCksCiAgICAgICAgdGltZW91dE1pbnV0ZXM6IE51bWJlcihyZXN1bHQudGltZW91dE1pbnV0ZXMpIHx8IG1pbnV0ZXMsCiAgICAgIH07CiAgICAgIHNldFJ1bnRpbWUobmV4dCk7CiAgICAgIHdyaXRlUnVudGltZShuZXh0KTsKICAgICAgdHJ5IHsKICAgICAgICB3aW5kb3cubG9jYWxTdG9yYWdlLnNldEl0ZW0oQUNUSVZJVFlfS0VZLCBTdHJpbmcobm93KSk7CiAgICAgIH0gY2F0Y2gge30KICAgICAgcmV0dXJuOwogICAgfQogICAgaWYgKFs0MDEsIDQwMywgNDIzXS5pbmNsdWRlcyhyZXN1bHQuc3RhdHVzKSkgewogICAgICBzZXRFeHBpcmVkKHRydWUpOwogICAgICBleHBpcmVkUmVmLmN1cnJlbnQgPSB0cnVlOwogICAgfQogIH0sIFtydW50aW1lPy50aW1lb3V0TWludXRlc10pOwoKICB1c2VFZmZlY3QoKCkgPT4gewogICAgY29uc3QgZXZlbnRzID0gWydwb2ludGVyZG93bicsICdrZXlkb3duJywgJ3RvdWNoc3RhcnQnLCAnd2hlZWwnLCAnc2Nyb2xsJywgJ21vdXNlbW92ZSddOwogICAgY29uc3QgaGFuZGxlciA9ICgpID0+IHsKICAgICAgaWYgKGV4cGlyZWRSZWYuY3VycmVudCkgcmV0dXJuOwogICAgICBjb25zdCBub3cgPSBEYXRlLm5vdygpOwogICAgICBjb25zdCBtaW51dGVzID0gcnVudGltZT8udGltZW91dE1pbnV0ZXMgfHwgREVGQVVMVF9NSU5VVEVTOwoKICAgICAgaWYgKG5vdyAtIGxhc3RMb2NhbEFjdGl2aXR5UmVmLmN1cnJlbnQgPj0gMTAwMCkgewogICAgICAgIGxhc3RMb2NhbEFjdGl2aXR5UmVmLmN1cnJlbnQgPSBub3c7CiAgICAgICAgY29uc3Qgb3B0aW1pc3RpYyA9IHsKICAgICAgICAgIGV4cGlyZXNBdDogbm93ICsgbWludXRlcyAqIDYwICogMTAwMCwKICAgICAgICAgIHRpbWVvdXRNaW51dGVzOiBtaW51dGVzLAogICAgICAgIH07CiAgICAgICAgc2V0UnVudGltZShvcHRpbWlzdGljKTsKICAgICAgICB3cml0ZVJ1bnRpbWUob3B0aW1pc3RpYyk7CiAgICAgICAgc2V0UmVtYWluaW5nKG9wdGltaXN0aWMuZXhwaXJlc0F0IC0gbm93KTsKICAgICAgfQoKICAgICAgdHJ5IHsKICAgICAgICB3aW5kb3cubG9jYWxTdG9yYWdlLnNldEl0ZW0oQUNUSVZJVFlfS0VZLCBTdHJpbmcobm93KSk7CiAgICAgIH0gY2F0Y2gge30KICAgICAgdm9pZCB0b3VjaCgpOwogICAgfTsKICAgIGV2ZW50cy5mb3JFYWNoKChldmVudCkgPT4gd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoZXZlbnQsIGhhbmRsZXIsIHsgcGFzc2l2ZTogdHJ1ZSB9KSk7CiAgICBjb25zdCBvblN0b3JhZ2UgPSAoZXZlbnQpID0+IHsKICAgICAgaWYgKGV2ZW50LmtleSA9PT0gUlVOVElNRV9LRVkpIHsKICAgICAgICBjb25zdCBuZXh0ID0gcmVhZFJ1bnRpbWUoKTsKICAgICAgICBpZiAobmV4dCkgewogICAgICAgICAgc2V0UnVudGltZShuZXh0KTsKICAgICAgICAgIHNldEV4cGlyZWQoZmFsc2UpOwogICAgICAgICAgZXhwaXJlZFJlZi5jdXJyZW50ID0gZmFsc2U7CiAgICAgICAgfQogICAgICB9CiAgICAgIGlmIChldmVudC5rZXkgPT09IEFDVElWSVRZX0tFWSkgewogICAgICAgIGNvbnN0IG5vdyA9IERhdGUubm93KCk7CiAgICAgICAgaWYgKG5vdyAtIGxhc3RDcm9zc1RhYlN5bmNSZWYuY3VycmVudCA+PSBUT1VDSF9USFJPVFRMRV9NUykgewogICAgICAgICAgbGFzdENyb3NzVGFiU3luY1JlZi5jdXJyZW50ID0gbm93OwogICAgICAgICAgdm9pZCBzeW5jRnJvbVNlcnZlcigpOwogICAgICAgIH0KICAgICAgfQogICAgfTsKICAgIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdzdG9yYWdlJywgb25TdG9yYWdlKTsKICAgIHJldHVybiAoKSA9PiB7CiAgICAgIGV2ZW50cy5mb3JFYWNoKChldmVudCkgPT4gd2luZG93LnJlbW92ZUV2ZW50TGlzdGVuZXIoZXZlbnQsIGhhbmRsZXIpKTsKICAgICAgd2luZG93LnJlbW92ZUV2ZW50TGlzdGVuZXIoJ3N0b3JhZ2UnLCBvblN0b3JhZ2UpOwogICAgfTsKICB9LCBbcnVudGltZT8udGltZW91dE1pbnV0ZXMsIHN5bmNGcm9tU2VydmVyLCB0b3VjaF0pOwoKICB1c2VFZmZlY3QoKCkgPT4gewogICAgaWYgKCFydW50aW1lPy5leHBpcmVzQXQpIHJldHVybiB1bmRlZmluZWQ7CiAgICBjb25zdCB0aWNrID0gKCkgPT4gewogICAgICBjb25zdCBsZWZ0ID0gcnVudGltZS5leHBpcmVzQXQgLSBEYXRlLm5vdygpOwogICAgICBpZiAobGVmdCA8PSAwKSB7CiAgICAgICAgc2V0UmVtYWluaW5nKDApOwogICAgICAgIGlmICghZXhwaXJlZFJlZi5jdXJyZW50KSB7CiAgICAgICAgICBleHBpcmVkUmVmLmN1cnJlbnQgPSB0cnVlOwogICAgICAgICAgc2V0RXhwaXJlZCh0cnVlKTsKICAgICAgICB9CiAgICAgICAgcmV0dXJuOwogICAgICB9CiAgICAgIHNldFJlbWFpbmluZyhsZWZ0KTsKICAgIH07CiAgICB0aWNrKCk7CiAgICBjb25zdCB0aW1lciA9IHdpbmRvdy5zZXRJbnRlcnZhbCh0aWNrLCAxMDAwKTsKICAgIHJldHVybiAoKSA9PiB3aW5kb3cuY2xlYXJJbnRlcnZhbCh0aW1lcik7CiAgfSwgW3J1bnRpbWU/LmV4cGlyZXNBdF0pOwoKICBjb25zdCBleHRlbmQgPSB1c2VDYWxsYmFjayhhc3luYyAobWludXRlcykgPT4gewogICAgaWYgKCFBTExPV0VEX01JTlVURVMuaW5jbHVkZXMobWludXRlcykgfHwgZXhwaXJlZFJlZi5jdXJyZW50KSByZXR1cm47CiAgICBjb25zdCByZXN1bHQgPSBhd2FpdCBzZXNzaW9uTXV0YXRpb24oJ0VYVEVORCcsIG1pbnV0ZXMpOwogICAgaWYgKCFyZXN1bHQub2sgfHwgIXJlc3VsdC5leHBpcmVzQXQpIHsKICAgICAgaWYgKFs0MDEsIDQwMywgNDIzXS5pbmNsdWRlcyhyZXN1bHQuc3RhdHVzKSkgewogICAgICAgIGV4cGlyZWRSZWYuY3VycmVudCA9IHRydWU7CiAgICAgICAgc2V0RXhwaXJlZCh0cnVlKTsKICAgICAgfQogICAgICByZXR1cm47CiAgICB9CiAgICBjb25zdCBuZXh0ID0gewogICAgICBleHBpcmVzQXQ6IERhdGUucGFyc2UocmVzdWx0LmV4cGlyZXNBdCksCiAgICAgIHRpbWVvdXRNaW51dGVzOiBtaW51dGVzLAogICAgfTsKICAgIHNldFJ1bnRpbWUobmV4dCk7CiAgICB3cml0ZVJ1bnRpbWUobmV4dCk7CiAgICBzZXRSZW1haW5pbmcobmV4dC5leHBpcmVzQXQgLSBEYXRlLm5vdygpKTsKICAgIHNldE9wZW4oZmFsc2UpOwogICAgc2V0Tm90aWNlKGBZb3VyIHNlc3Npb24gaGFzIGJlZW4gZXh0ZW5kZWQgYnkgJHttaW51dGVzfSBtaW51dGVzLmApOwogICAgd2luZG93LnNldFRpbWVvdXQoKCkgPT4gc2V0Tm90aWNlKCcnKSwgMzAwMCk7CiAgfSwgW10pOwoKICBjb25zdCBkaXNwbGF5ID0gdXNlTWVtbygoKSA9PiB7CiAgICBpZiAocmVtYWluaW5nID09PSBudWxsKSByZXR1cm4gJy0tOi0tJzsKICAgIHJldHVybiBmb3JtYXRSZW1haW5pbmcocmVtYWluaW5nKTsKICB9LCBbcmVtYWluaW5nXSk7CgogIGNvbnN0IGhhbmRsZUxvZ2luQWdhaW4gPSBhc3luYyAoKSA9PiB7CiAgICB0cnkgewogICAgICB3aW5kb3cubG9jYWxTdG9yYWdlLnJlbW92ZUl0ZW0oUlVOVElNRV9LRVkpOwogICAgICB3aW5kb3cubG9jYWxTdG9yYWdlLnJlbW92ZUl0ZW0oQUNUSVZJVFlfS0VZKTsKICAgIH0gY2F0Y2gge30KICAgIHRyeSB7CiAgICAgIGF3YWl0IGZldGNoKCcvYXBpL2F1dGgvbG9nb3V0JywgewogICAgICAgIG1ldGhvZDogJ1BPU1QnLAogICAgICAgIGNyZWRlbnRpYWxzOiAnaW5jbHVkZScsCiAgICAgICAgY2FjaGU6ICduby1zdG9yZScsCiAgICAgICAga2VlcGFsaXZlOiB0cnVlLAogICAgICAgIGhlYWRlcnM6IHsgQWNjZXB0OiAnYXBwbGljYXRpb24vanNvbicgfSwKICAgICAgfSk7CiAgICB9IGNhdGNoIHt9CiAgICB3aW5kb3cubG9jYXRpb24ucmVwbGFjZSgnaHR0cHM6Ly9idWRkeWZsZWV0cy5pbi9sb2dpbicpOwogIH07CgogIHJldHVybiAoCiAgICA8PgogICAgICA8ZGl2IGNsYXNzTmFtZT0icmVsYXRpdmUgaGlkZGVuIHhsOmJsb2NrIj4KICAgICAgICA8YnV0dG9uCiAgICAgICAgICB0eXBlPSJidXR0b24iCiAgICAgICAgICBvbkNsaWNrPXsoKSA9PiBzZXRPcGVuKCh2YWx1ZSkgPT4gIXZhbHVlKX0KICAgICAgICAgIGNsYXNzTmFtZT0iZmxleCBtaW4tdy1bMTEycHhdIGZsZXgtY29sIGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWNlbnRlciByb3VuZGVkLW1kIGJvcmRlciBib3JkZXItd2hpdGUvMjAgYmctd2hpdGUvWy4wOF0gcHgtMyBweS0xLjUgdGV4dC1jZW50ZXIgdGV4dC13aGl0ZSBzaGFkb3ctW2luc2V0XzBfMXB4XzBfcmdiYSgyNTUsMjU1LDI1NSwuMTIpLDBfMXB4XzJweF9yZ2JhKDAsMCwwLC4wOCldIGJhY2tkcm9wLWJsdXItc20gdHJhbnNpdGlvbiBob3Zlcjpib3JkZXItd2hpdGUvMzUgaG92ZXI6Ymctd2hpdGUvWy4xNF0iCiAgICAgICAgICBhcmlhLWxhYmVsPSJTZXNzaW9uIGNvbnRyb2xzIgogICAgICAgID4KICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0iZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTEgdGV4dC1bOHB4XSBmb250LWJvbGQgdXBwZXJjYXNlIHRyYWNraW5nLVsuMTJlbV0gdGV4dC1bdmFyKC0tYmYtaGVhZGVyLW11dGVkKV0iPgogICAgICAgICAgICA8Q2xvY2szIHNpemU9ezl9IC8+IFNlc3Npb24KICAgICAgICAgIDwvc3Bhbj4KICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0idGV4dC1bMTFweF0gZm9udC1ib2xkIHRhYnVsYXItbnVtcyB0ZXh0LVt2YXIoLS1iZi1oZWFkZXItdGV4dCldIj57ZGlzcGxheX08L3NwYW4+CiAgICAgICAgPC9idXR0b24+CgogICAgICAgIHtvcGVuICYmICFleHBpcmVkID8gKAogICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIHJpZ2h0LTAgdG9wLVtjYWxjKDEwMCUrOHB4KV0gei1bODBdIHctWzMxMHB4XSBvdmVyZmxvdy1oaWRkZW4gcm91bmRlZC14bCBib3JkZXIgYm9yZGVyLVt2YXIoLS1iZi1ib3JkZXIpXSBiZy1bdmFyKC0tYmYtc3VyZmFjZSldIHAtMyBzaGFkb3ctMnhsIj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9Im1iLTMgZmxleCBpdGVtcy1jZW50ZXIganVzdGlmeS1iZXR3ZWVuIj4KICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InRleHQtWzEycHhdIGZvbnQtYm9sZCB0ZXh0LVt2YXIoLS1iZi10ZXh0KV0iPlNlc3Npb24gdGltZTwvZGl2PgogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9Im10LTAuNSB0ZXh0LVs5cHhdIHRleHQtW3ZhcigtLWJmLXRleHQtMyldIj5DaG9vc2UgaG93IGxvbmcgdGhlIGluYWN0aXZpdHkgd2luZG93IHNob3VsZCBiZS48L2Rpdj4KICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICA8VGltZXJSZXNldCBzaXplPXsxNn0gY2xhc3NOYW1lPSJ0ZXh0LVt2YXIoLS1iZi1wcmltYXJ5KV0iIC8+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZ3JpZCBncmlkLWNvbHMtMyBnYXAtMiI+CiAgICAgICAgICAgICAge0FMTE9XRURfTUlOVVRFUy5tYXAoKG1pbnV0ZXMpID0+ICgKICAgICAgICAgICAgICAgIDxidXR0b24KICAgICAgICAgICAgICAgICAga2V5PXttaW51dGVzfQogICAgICAgICAgICAgICAgICB0eXBlPSJidXR0b24iCiAgICAgICAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHZvaWQgZXh0ZW5kKG1pbnV0ZXMpfQogICAgICAgICAgICAgICAgICBjbGFzc05hbWU9InJvdW5kZWQtbGcgYm9yZGVyIGJvcmRlci1bdmFyKC0tYmYtYm9yZGVyKV0gYmctW3ZhcigtLWJmLXN1cmZhY2UtMildIHB4LTIgcHktMyB0ZXh0LWNlbnRlciB0cmFuc2l0aW9uIGhvdmVyOmJvcmRlci1bdmFyKC0tYmYtcHJpbWFyeSldIGhvdmVyOmJnLVtyZ2IodmFyKC0tYmYtcHJpbWFyeS1yZ2IpLy4wOCldIgogICAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0idGV4dC1bMTJweF0gZm9udC1ib2xkIHRleHQtW3ZhcigtLWJmLXRleHQpXSI+e21pbnV0ZXN9IG1pbjwvZGl2PgogICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXQtMSB0ZXh0LVs4cHhdIHRleHQtW3ZhcigtLWJmLXRleHQtMyldIj5FeHRlbmQgc2Vzc2lvbjwvZGl2PgogICAgICAgICAgICAgICAgPC9idXR0b24+CiAgICAgICAgICAgICAgKSl9CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgKSA6IG51bGx9CiAgICAgIDwvZGl2PgoKICAgICAge25vdGljZSA/ICgKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZml4ZWQgcmlnaHQtNSB0b3AtNSB6LVsxMjBdIGZsZXggaXRlbXMtY2VudGVyIGdhcC0yIHJvdW5kZWQtbGcgYm9yZGVyIGJvcmRlci1lbWVyYWxkLTQwMC8zMCBiZy1bdmFyKC0tYmYtc3VyZmFjZSldIHB4LTQgcHktMyB0ZXh0LVsxMXB4XSBmb250LXNlbWlib2xkIHRleHQtW3ZhcigtLWJmLXRleHQpXSBzaGFkb3ctMnhsIj4KICAgICAgICAgIDxTaGllbGRBbGVydCBzaXplPXsxNX0gY2xhc3NOYW1lPSJ0ZXh0LWVtZXJhbGQtNTAwIiAvPgogICAgICAgICAge25vdGljZX0KICAgICAgICA8L2Rpdj4KICAgICAgKSA6IG51bGx9CgogICAgICB7ZXhwaXJlZCA/ICgKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZml4ZWQgaW5zZXQtMCB6LVsyMDBdIGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIGJnLXNsYXRlLTk1MC83NSBweC00IGJhY2tkcm9wLWJsdXItc20iPgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9InctZnVsbCBtYXgtdy1bNDQwcHhdIHJvdW5kZWQtMnhsIGJvcmRlciBib3JkZXItW3ZhcigtLWJmLWJvcmRlcildIGJnLVt2YXIoLS1iZi1zdXJmYWNlKV0gcC03IHRleHQtY2VudGVyIHNoYWRvdy0yeGwiPgogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXgtYXV0byBmbGV4IGgtMTQgdy0xNCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgcm91bmRlZC1mdWxsIGJnLXJvc2UtNTAwLzEwIHRleHQtcm9zZS01MDAiPgogICAgICAgICAgICAgIDxTaGllbGRBbGVydCBzaXplPXsyNn0gLz4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDxoMiBjbGFzc05hbWU9Im10LTQgdGV4dC1bMjBweF0gZm9udC1ib2xkIHRleHQtW3ZhcigtLWJmLXRleHQpXSI+U2Vzc2lvbiBleHBpcmVkPC9oMj4KICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJteC1hdXRvIG10LTIgbWF4LXctWzM1MHB4XSB0ZXh0LVsxMXB4XSBsZWFkaW5nLTUgdGV4dC1bdmFyKC0tYmYtdGV4dC0yKV0iPgogICAgICAgICAgICAgIFlvdXIgc2Vzc2lvbiBoYXMgZXhwaXJlZCBkdWUgdG8gaW5hY3Rpdml0eS4gRm9yIHlvdXIgc2VjdXJpdHksIHBsZWFzZSBsb2cgaW4gYWdhaW4gdG8gY29udGludWUuCiAgICAgICAgICAgIDwvcD4KICAgICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICAgIHR5cGU9ImJ1dHRvbiIKICAgICAgICAgICAgICBvbkNsaWNrPXtoYW5kbGVMb2dpbkFnYWlufQogICAgICAgICAgICAgIGNsYXNzTmFtZT0ibXQtNSBpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgcm91bmRlZC1tZCBib3JkZXIgYm9yZGVyLVt2YXIoLS1iZi1wcmltYXJ5KV0gYmctW3ZhcigtLWJmLXByaW1hcnkpXSBweC01IHB5LTIuNSB0ZXh0LVsxMXB4XSBmb250LWJvbGQgdGV4dC13aGl0ZSBzaGFkb3ctc20gdHJhbnNpdGlvbiBob3ZlcjpiZy1bdmFyKC0tYmYtcHJpbWFyeS1zdHJvbmcpXSIKICAgICAgICAgICAgPgogICAgICAgICAgICAgIExvZ2luIGFnYWluCiAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICkgOiBudWxsfQogICAgPC8+CiAgKTsKfQo=')
[System.IO.File]::WriteAllBytes($componentPath, $componentBytes)

# Disable only the old App-level auto-timeout redirect.
# The new SessionControl owns inactivity UX and expiry.
Backup-Once $appPath
$app = Read-Utf8NoBom $appPath

$pattern = "(?s)(const handleLogout\s*=\s*useCallback\(\s*\(\s*isAutoTimeout\s*=\s*false\s*\)\s*=>\s*\{)"
$replacement = '$1' + "`r`n" + "      if (isAutoTimeout) {`r`n        window.dispatchEvent(new CustomEvent('bf-session-legacy-timeout'));`r`n        return;`r`n      }`r`n"
$patched = [regex]::Replace($app, $pattern, $replacement, 1)
if ($patched -eq $app) {
    throw 'Could not locate App.jsx handleLogout function.'
}
$app = $patched

$app = $app.Replace("const INACTIVITY_TIMEOUT_MS =`r`n    60 * 60 * 1000;", "const INACTIVITY_TIMEOUT_MS =`r`n    30 * 60 * 1000;")
$app = $app.Replace("const INACTIVITY_TIMEOUT_MS =`n    60 * 60 * 1000;", "const INACTIVITY_TIMEOUT_MS =`n    30 * 60 * 1000;")

Write-Utf8NoBom $appPath $app

function Patch-Countdown([string]$Path, [string]$ImportPath) {
    Backup-Once $Path
    $text = Read-Utf8NoBom $Path

    if (-not $text.Contains("SessionControl from")) {
        $text = "import SessionControl from '$ImportPath';`r`n" + $text
    }

    $start = $text.IndexOf('function SessionCountdown()')
    if ($start -lt 0) {
        throw "SessionCountdown not found in $Path"
    }

    $brace = $text.IndexOf('{', $start)
    if ($brace -lt 0) {
        throw "SessionCountdown opening brace not found in $Path"
    }

    $depth = 0
    $end = -1
    for ($i = $brace; $i -lt $text.Length; $i++) {
        if ($text[$i] -eq '{') {
            $depth++
        } elseif ($text[$i] -eq '}') {
            $depth--
            if ($depth -eq 0) {
                $end = $i + 1
                break
            }
        }
    }

    if ($end -lt 0) {
        throw "SessionCountdown closing brace not found in $Path"
    }

    $replacement = "function SessionCountdown() {`r`n  return <SessionControl />;`r`n}"
    $text = $text.Substring(0, $start) + $replacement + $text.Substring($end)
    Write-Utf8NoBom $Path $text
}

Patch-Countdown $devLayoutPath '../components/SessionControl'
Patch-Countdown $portalLayoutPath '../../components/SessionControl'

# Add POST TOUCH / EXTEND support to /api/auth/session.
Backup-Once $sessionApiPath
$api = Read-Utf8NoBom $sessionApiPath

if (-not $api.Contains('async function handleSessionActivityMutation')) {
    $helperText = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('CmFzeW5jIGZ1bmN0aW9uIGhhbmRsZVNlc3Npb25BY3Rpdml0eU11dGF0aW9uKHJlcSwgcmVzKSB7CiAgY29uc3QgcmVxdWVzdEhvc3QgPSBnZXRSZXF1ZXN0SG9zdChyZXEpOwoKICBpZiAoIXJlcXVlc3RIb3N0IHx8ICFpc1BvcnRhbEhvc3QocmVxdWVzdEhvc3QpKSB7CiAgICBjbGVhclNlc3Npb25Db29raWUocmVzKTsKICAgIHJldHVybiBzZW5kSnNvbihyZXMsIDQwMywgeyBvazogZmFsc2UsIGNvZGU6ICdQT1JUQUxfTk9UX0FMTE9XRUQnIH0pOwogIH0KCiAgaWYgKCFvcmlnaW5NYXRjaGVzSG9zdChyZXEsIHJlcXVlc3RIb3N0KSkgewogICAgcmV0dXJuIHNlbmRKc29uKHJlcywgNDAzLCB7IG9rOiBmYWxzZSwgY29kZTogJ09SSUdJTl9OT1RfQUxMT1dFRCcgfSk7CiAgfQoKICBjb25zdCBzZWNGZXRjaFNpdGUgPSBTdHJpbmcocmVxLmhlYWRlcnNbJ3NlYy1mZXRjaC1zaXRlJ10gfHwgJycpLnRvTG93ZXJDYXNlKCk7CiAgaWYgKHNlY0ZldGNoU2l0ZSAmJiAhWydzYW1lLW9yaWdpbicsICdub25lJ10uaW5jbHVkZXMoc2VjRmV0Y2hTaXRlKSkgewogICAgcmV0dXJuIHNlbmRKc29uKHJlcywgNDAzLCB7IG9rOiBmYWxzZSwgY29kZTogJ0NST1NTX1NJVEVfUkVRVUVTVF9CTE9DS0VEJyB9KTsKICB9CgogIGNvbnN0IGNvb2tpZXMgPSBwYXJzZUNvb2tpZXMocmVxLmhlYWRlcnMuY29va2llKTsKICBjb25zdCBzZXNzaW9uVG9rZW4gPSBjb29raWVzW0NPT0tJRV9OQU1FXTsKCiAgaWYgKCFzZXNzaW9uVG9rZW4gfHwgc2Vzc2lvblRva2VuLmxlbmd0aCA8IDIwIHx8IHNlc3Npb25Ub2tlbi5sZW5ndGggPiAyMDApIHsKICAgIGNsZWFyU2Vzc2lvbkNvb2tpZShyZXMpOwogICAgcmV0dXJuIHNlbmRKc29uKHJlcywgNDAxLCB7IG9rOiBmYWxzZSwgY29kZTogJ1NFU1NJT05fUkVRVUlSRUQnIH0pOwogIH0KCiAgbGV0IHNlY3VyaXR5U2Vzc2lvbjsKICB0cnkgewogICAgc2VjdXJpdHlTZXNzaW9uID0gYXdhaXQgZ2V0U2VjdXJpdHlTZXNzaW9uKHNlc3Npb25Ub2tlbik7CiAgfSBjYXRjaCAoZXJyb3IpIHsKICAgIGNvbnNvbGUuZXJyb3IoJ1Nlc3Npb24gYWN0aXZpdHkgbG9va3VwIGZhaWxlZDonLCBlcnJvcj8ubWVzc2FnZSk7CiAgICByZXR1cm4gc2VuZEpzb24ocmVzLCA1MDMsIHsgb2s6IGZhbHNlLCBjb2RlOiAnU0VDVVJJVFlfU0VSVklDRV9VTkFWQUlMQUJMRScgfSk7CiAgfQoKICBpZiAoIXNlY3VyaXR5U2Vzc2lvbikgewogICAgY2xlYXJTZXNzaW9uQ29va2llKHJlcyk7CiAgICByZXR1cm4gc2VuZEpzb24ocmVzLCA0MDEsIHsgb2s6IGZhbHNlLCBjb2RlOiAnU0VTU0lPTl9JTlZBTElEJyB9KTsKICB9CgogIGNvbnN0IG5vdyA9IERhdGUubm93KCk7CiAgY29uc3QgY3VycmVudEV4cGlyeSA9IG5ldyBEYXRlKHNlY3VyaXR5U2Vzc2lvbi5odHRwX3Nlc3Npb25fZXhwaXJlc19hdCkuZ2V0VGltZSgpOwoKICBpZiAoIU51bWJlci5pc0Zpbml0ZShjdXJyZW50RXhwaXJ5KSB8fCBjdXJyZW50RXhwaXJ5IDw9IG5vdykgewogICAgYXdhaXQgaW52YWxpZGF0ZVNlc3Npb24oewogICAgICBzZXNzaW9uSWQ6IHNlY3VyaXR5U2Vzc2lvbi5pZCwKICAgICAgcmVhc29uOiAnSFRUUF9TRVNTSU9OX0VYUElSRUQnLAogICAgICBleHBpcmVkOiB0cnVlLAogICAgfSk7CiAgICBjbGVhclNlc3Npb25Db29raWUocmVzKTsKICAgIHJldHVybiBzZW5kSnNvbihyZXMsIDQwMSwgeyBvazogZmFsc2UsIGNvZGU6ICdTRVNTSU9OX0VYUElSRUQnIH0pOwogIH0KCiAgY29uc3QgYWNjb3VudFNlY3VyaXR5ID0gYXdhaXQgZ2V0QWNjb3VudFNlY3VyaXR5KHNlY3VyaXR5U2Vzc2lvbi51c2VyX2lkKTsKICBpZiAoIWFjY291bnRTZWN1cml0eSB8fCBhY2NvdW50U2VjdXJpdHkuaXNfbG9ja2VkKSB7CiAgICBhd2FpdCBpbnZhbGlkYXRlU2Vzc2lvbih7CiAgICAgIHNlc3Npb25JZDogc2VjdXJpdHlTZXNzaW9uLmlkLAogICAgICByZWFzb246ICdBQ0NPVU5UX1NFQ1VSSVRZX0xPQ0snLAogICAgfSk7CiAgICBjbGVhclNlc3Npb25Db29raWUocmVzKTsKICAgIHJldHVybiBzZW5kSnNvbihyZXMsIDQyMywgeyBvazogZmFsc2UsIGNvZGU6ICdBQ0NPVU5UX0xPQ0tFRCcgfSk7CiAgfQoKICBjb25zdCBjdXJyZW50SXAgPSBnZXRDbGllbnRJcChyZXEpOwogIGlmIChzZWN1cml0eVNlc3Npb24uaXBfYWRkcmVzcyAmJiAoIWN1cnJlbnRJcCB8fCBTdHJpbmcoY3VycmVudElwKSAhPT0gU3RyaW5nKHNlY3VyaXR5U2Vzc2lvbi5pcF9hZGRyZXNzKSkpIHsKICAgIGF3YWl0IGludmFsaWRhdGVTZXNzaW9uKHsKICAgICAgc2Vzc2lvbklkOiBzZWN1cml0eVNlc3Npb24uaWQsCiAgICAgIHJlYXNvbjogJ0lQX0NIQU5HRUQnLAogICAgfSk7CiAgICBjbGVhclNlc3Npb25Db29raWUocmVzKTsKICAgIHJldHVybiBzZW5kSnNvbihyZXMsIDQwMSwgeyBvazogZmFsc2UsIGNvZGU6ICdTRUNVUklUWV9DT05URVhUX0NIQU5HRUQnIH0pOwogIH0KCiAgY29uc3QgY3VycmVudFVzZXJBZ2VudCA9IGdldFVzZXJBZ2VudChyZXEpOwogIGlmIChzZWN1cml0eVNlc3Npb24udXNlcl9hZ2VudCAmJiBjdXJyZW50VXNlckFnZW50ICE9PSBzZWN1cml0eVNlc3Npb24udXNlcl9hZ2VudCkgewogICAgYXdhaXQgaW52YWxpZGF0ZVNlc3Npb24oewogICAgICBzZXNzaW9uSWQ6IHNlY3VyaXR5U2Vzc2lvbi5pZCwKICAgICAgcmVhc29uOiAnQlJPV1NFUl9DSEFOR0VEJywKICAgIH0pOwogICAgY2xlYXJTZXNzaW9uQ29va2llKHJlcyk7CiAgICByZXR1cm4gc2VuZEpzb24ocmVzLCA0MDEsIHsgb2s6IGZhbHNlLCBjb2RlOiAnU0VDVVJJVFlfQ09OVEVYVF9DSEFOR0VEJyB9KTsKICB9CgogIGNvbnN0IHJlcXVlc3RlZEFjdGlvbiA9IFN0cmluZyhyZXEuYm9keT8uYWN0aW9uIHx8ICdUT1VDSCcpLnRyaW0oKS50b1VwcGVyQ2FzZSgpOwogIGNvbnN0IHJlcXVlc3RlZE1pbnV0ZXMgPSBOdW1iZXIocmVxLmJvZHk/LnRpbWVvdXRNaW51dGVzKTsKICBjb25zdCB0aW1lb3V0TWludXRlcyA9IFszMCwgNjAsIDkwXS5pbmNsdWRlcyhyZXF1ZXN0ZWRNaW51dGVzKSA/IHJlcXVlc3RlZE1pbnV0ZXMgOiAzMDsKCiAgaWYgKCFbJ1RPVUNIJywgJ0VYVEVORCddLmluY2x1ZGVzKHJlcXVlc3RlZEFjdGlvbikpIHsKICAgIHJldHVybiBzZW5kSnNvbihyZXMsIDQwMCwgeyBvazogZmFsc2UsIGNvZGU6ICdJTlZBTElEX1NFU1NJT05fQUNUSU9OJyB9KTsKICB9CgogIGNvbnN0IG5leHRFeHBpcnkgPSBuZXcgRGF0ZShub3cgKyB0aW1lb3V0TWludXRlcyAqIDYwICogMTAwMCkudG9JU09TdHJpbmcoKTsKCiAgY29uc3QgeyBlcnJvcjogdXBkYXRlRXJyb3IgfSA9IGF3YWl0IHN1cGFiYXNlQWRtaW4KICAgIC5mcm9tKCdzZWN1cml0eV9zZXNzaW9ucycpCiAgICAudXBkYXRlKHsKICAgICAgbGFzdF9zZWVuX2F0OiBuZXcgRGF0ZShub3cpLnRvSVNPU3RyaW5nKCksCiAgICAgIGh0dHBfc2Vzc2lvbl9leHBpcmVzX2F0OiBuZXh0RXhwaXJ5LAogICAgfSkKICAgIC5lcSgnaWQnLCBzZWN1cml0eVNlc3Npb24uaWQpCiAgICAuZXEoJ3N0YXR1cycsICdhY3RpdmUnKTsKCiAgaWYgKHVwZGF0ZUVycm9yKSB7CiAgICBjb25zb2xlLmVycm9yKCdTZXNzaW9uIGFjdGl2aXR5IHVwZGF0ZSBmYWlsZWQ6JywgdXBkYXRlRXJyb3IubWVzc2FnZSk7CiAgICByZXR1cm4gc2VuZEpzb24ocmVzLCA1MDMsIHsgb2s6IGZhbHNlLCBjb2RlOiAnU0VDVVJJVFlfU0VSVklDRV9VTkFWQUlMQUJMRScgfSk7CiAgfQoKICByZXR1cm4gc2VuZEpzb24ocmVzLCAyMDAsIHsKICAgIG9rOiB0cnVlLAogICAgYWN0aW9uOiByZXF1ZXN0ZWRBY3Rpb24sCiAgICBzZXNzaW9uOiB7CiAgICAgIGV4cGlyZXNBdDogbmV4dEV4cGlyeSwKICAgICAgdGltZW91dE1pbnV0ZXMsCiAgICAgIGxhc3RTZWVuQXQ6IG5ldyBEYXRlKG5vdykudG9JU09TdHJpbmcoKSwKICAgIH0sCiAgICBleHBpcmVzQXQ6IG5leHRFeHBpcnksCiAgICB0aW1lb3V0TWludXRlcywKICB9KTsKfQo='))
    $handlerMarker = 'export default async function handler('
    $pos = $api.IndexOf($handlerMarker)
    if ($pos -lt 0) {
        throw 'Could not locate /api/auth/session handler.'
    }
    $api = $api.Insert($pos, $helperText + "`r`n`r`n")
}

if ($api.Contains("req.method !==`r`n    'GET'")) {
    $api = $api.Replace(
        "req.method !==`r`n    'GET'",
        "!['GET', 'POST'].includes(`r`n      req.method`r`n    )"
    )
} elseif ($api.Contains("req.method !==`n    'GET'")) {
    $api = $api.Replace(
        "req.method !==`n    'GET'",
        "!['GET', 'POST'].includes(`n      req.method`n    )"
    )
} elseif (-not $api.Contains("!['GET', 'POST'].includes")) {
    throw 'Could not update session API method guard.'
}

if (-not $api.Contains('SESSION ACTIVITY / EXTENSION')) {
    $marker = "  /* ========================================================`r`n     GET ONLY"
    $branch = @'
  /* ========================================================
     SESSION ACTIVITY / EXTENSION
  ======================================================== */

  if (
    req.method ===
    'POST'
  ) {
    return await handleSessionActivityMutation(
      req,
      res
    );
  }

'@
    if ($api.Contains($marker)) {
        $api = $api.Replace($marker, $branch + $marker)
    } else {
        $marker = "  /* ========================================================`n     GET ONLY"
        if ($api.Contains($marker)) {
            $api = $api.Replace($marker, $branch + $marker)
        } else {
            throw 'Could not insert POST session branch.'
        }
    }
}

Write-Utf8NoBom $sessionApiPath $api

Write-Host ''
Write-Host 'SUCCESS: Buddy Fleets MFA + inactivity session system patch applied.'
Write-Host 'Created: src\components\SessionControl.jsx'
Write-Host 'Updated: src\App.jsx'
Write-Host 'Updated: src\layouts\DeveloperLayout.jsx'
Write-Host 'Updated: src\clientPortal\components\UniversalDashboardShell.jsx'
Write-Host 'Updated: api\auth\session.js'
Write-Host 'Backups: *.before-session-system.bak'
