import React, { useMemo, useState } from 'react';
import { Building2, Calendar, Download, FileText, IndianRupee, Truck, UsersRound } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import KpiCard from '../components/KpiCard';
import DataTable from '../components/DataTable';
import { useClientPortal } from '../ClientPortalContext';

function firstValue(source, keys) {
  for (const key of keys) if (source?.[key] !== null && source?.[key] !== undefined && source?.[key] !== '') return source[key];
  return null;
}
function formatDate(value) {
  if (!value) return '—';
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' });
}
function money(value) { return `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits:2 })}`; }
function daysRemaining(value) {
  if (!value) return null;
  const end = new Date(value).getTime();
  if (!Number.isFinite(end)) return null;
  return Math.ceil((end - Date.now()) / 86400000);
}
function pdfEscape(value) { return String(value ?? '').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?'); }
function makeInvoicePdf({ company, invoice }) {
  const rows = [
    'BUDDY FLEETS',
    'Subscription Invoice',
    '',
    `Invoice: ${invoice.invoice_number || invoice.number || '—'}`,
    `Company: ${company?.company_name || company?.companyName || '—'}`,
    `Company Code: ${company?.company_code || company?.companyCode || '—'}`,
    `Invoice Date: ${formatDate(invoice.invoice_date || invoice.date)}`,
    `Billing Period: ${formatDate(invoice.billing_period_start)} - ${formatDate(invoice.billing_period_end)}`,
    `Status: ${String(invoice.status || '—').replaceAll('_',' ').toUpperCase()}`,
    `Subtotal: INR ${Number(invoice.subtotal || 0).toFixed(2)}`,
    `Taxable Amount: INR ${Number(invoice.taxable_amount || 0).toFixed(2)}`,
    `CGST: INR ${Number(invoice.cgst || 0).toFixed(2)}`,
    `SGST: INR ${Number(invoice.sgst || 0).toFixed(2)}`,
    `IGST: INR ${Number(invoice.igst || 0).toFixed(2)}`,
    `Grand Total: INR ${Number(invoice.grand_total || invoice.amount || 0).toFixed(2)}`,
    `Paid Amount: INR ${Number(invoice.paid_amount || 0).toFixed(2)}`,
    '',
    'System generated by Buddy Fleets.',
  ];
  const commands = ['BT','/F1 17 Tf','50 790 Td'];
  rows.forEach((line,index)=>{ if(index) commands.push('0 -24 Td'); commands.push(`(${pdfEscape(line)}) Tj`); });
  commands.push('ET');
  const stream = commands.join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${new TextEncoder().encode(stream).length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (let i=0;i<objects.length;i++) { offsets.push(new TextEncoder().encode(pdf).length); pdf += `${i+1} 0 obj\n${objects[i]}\nendobj\n`; }
  const xref = new TextEncoder().encode(pdf).length;
  pdf += `xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;
  for (let i=1;i<=objects.length;i++) pdf += `${String(offsets[i]).padStart(10,'0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new Blob([pdf], { type:'application/pdf' });
}

export default function SubscriptionPage({ section = '' }) {
  const { company, currentUser, data, sites = [] } = useClientPortal();
  const billing = data?.billing || {};
  const subscription = billing.subscription || {};
  const plan = billing.plan || currentUser?.effectivePlan || {};
  const limits = billing.limits || currentUser?.effectiveLimits || {};
  const invoices = billing.invoices || [];
  const payments = billing.payments || [];
  const receipts = billing.receipts || [];
  const users = data?.users || [];
  const vehicles = data?.vehicles || [];
  const usage = billing.usage || {};
  const startDate = firstValue(subscription, ['start_date','current_period_start','trial_start','created_at']);
  const endDate = firstValue(subscription, ['valid_until','end_date','current_period_end','trial_end','expires_at','expiry_date']);
  const remaining = daysRemaining(endDate);
  const status = subscription.status || company?.status || currentUser?.companyStatus || 'active';
  const [message,setMessage] = useState('');
  const planName = plan.name || plan.plan_name || plan.plan_key || subscription.plan_name || subscription.plan_id || 'Not assigned';
  const billingCycle = subscription.billing_cycle || subscription.interval || subscription.cycle || '—';
  const normalizedSection = String(section || '').split('/')[0];

  const usageRows = useMemo(()=>[
    { id:'vehicles', resource:'Vehicles', used:usage.vehicles ?? vehicles.length, limit:limits.vehicles_max ?? limits.vehicles ?? 'Unlimited' },
    { id:'users', resource:'Users', used:usage.users ?? users.length, limit:limits.users ?? 'Unlimited' },
    { id:'sites', resource:'Sites / Branches', used:usage.sites ?? sites.length, limit:limits.sites ?? limits.branches ?? 'Unlimited' },
  ],[vehicles.length,users.length,sites.length,limits,usage.vehicles,usage.users,usage.sites]);

  const download = (invoice) => {
    try {
      const blob = makeInvoicePdf({company,invoice});
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${invoice.invoice_number || 'Buddy-Fleets-Invoice'}.pdf`.replace(/[\\/:*?"<>|]/g,'-');
      document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
      setMessage('Invoice PDF generated successfully.');
    } catch { setMessage('Unable to generate invoice PDF.'); }
  };

  const invoiceColumns = [
    {key:'invoice_number',label:'Invoice No.'},
    {key:'invoice_date',label:'Invoice Date',render:formatDate},
    {key:'billing_period_end',label:'Billing Period End',render:formatDate},
    {key:'grand_total',label:'Amount',render:money},
    {key:'status',label:'Status',render:v=><span className={`bf-status ${v}`}>{String(v||'—').replaceAll('_',' ')}</span>},
    {key:'download',label:'Invoice',render:(_,row)=><button className="bf-btn bf-btn-secondary" onClick={()=>download(row)}><Download size={13}/> PDF</button>},
  ];

  const paymentColumns = [
    {key:'payment_date',label:'Date',render:formatDate},
    {key:'amount',label:'Amount',render:money},
    {key:'payment_mode',label:'Mode'},
    {key:'transaction_reference',label:'Reference'},
    {key:'status',label:'Status',render:v=><span className={`bf-status ${v}`}>{String(v||'—').replaceAll('_',' ')}</span>},
  ];

  return <>
    <PageHeader title="Subscription & Billing" subtitle="Plan validity, usage limits, subscription invoices and payment history." />
    {message ? <div className="bf-note" style={{marginBottom:14}}>{message}</div> : null}
    <div className="bf-grid bf-grid-4" style={{marginBottom:16}}>
      <KpiCard title="Current Plan" value={planName} icon={IndianRupee}/>
      <KpiCard title="Plan Status" value={String(status).replaceAll('_',' ')} icon={Calendar} tone={String(status).includes('active')?'green':'orange'}/>
      <KpiCard title="Valid Until" value={formatDate(endDate)} note={remaining===null?'Validity date unavailable':remaining>=0?`${remaining} days remaining`:`Expired ${Math.abs(remaining)} days ago`} icon={Calendar} tone={remaining!==null&&remaining<30?'orange':'green'}/>
      <KpiCard title="Billing Cycle" value={String(billingCycle).replaceAll('_',' ')} icon={FileText}/>
    </div>

    {(!normalizedSection || ['validity','usage'].includes(normalizedSection)) ? <div className="bf-grid bf-grid-2" style={{marginBottom:16}}>
      <div className="bf-card"><div className="bf-card-head"><h3>Plan & Validity</h3></div><div className="bf-card-body bf-list">
        <div className="bf-list-row"><span>Plan</span><strong>{planName}</strong></div>
        <div className="bf-list-row"><span>Status</span><strong>{String(status).replaceAll('_',' ')}</strong></div>
        <div className="bf-list-row"><span>Start Date</span><strong>{formatDate(startDate)}</strong></div>
        <div className="bf-list-row"><span>Valid Until</span><strong>{formatDate(endDate)}</strong></div>
        <div className="bf-list-row"><span>Billing Cycle</span><strong>{String(billingCycle).replaceAll('_',' ')}</strong></div>
      </div></div>
      <div className="bf-card"><div className="bf-card-head"><h3>Usage & Limits</h3></div><DataTable columns={[{key:'resource',label:'Resource'},{key:'used',label:'Used'},{key:'limit',label:'Plan Limit'}]} rows={usageRows}/></div>
    </div> : null}

    {(!normalizedSection || normalizedSection==='invoices') ? <div className="bf-card" style={{marginBottom:16}}><div className="bf-card-head"><h3>Invoices</h3><span className="bf-muted" style={{fontSize:10}}>{invoices.length} record(s)</span></div><DataTable columns={invoiceColumns} rows={invoices}/></div> : null}
    {(!normalizedSection || normalizedSection==='payments') ? <div className="bf-grid bf-grid-2">
      <div className="bf-card"><div className="bf-card-head"><h3>Payments</h3></div><DataTable columns={paymentColumns} rows={payments}/></div>
      <div className="bf-card"><div className="bf-card-head"><h3>Receipts</h3></div>{receipts.length ? <DataTable columns={[{key:'receipt_number',label:'Receipt No.'},{key:'issued_at',label:'Issued',render:formatDate}]} rows={receipts}/> : <div className="bf-card-body"><div className="bf-note">Verified payment receipts will appear here when available.</div></div>}</div>
    </div> : null}
    <div className="bf-grid bf-grid-3" style={{marginTop:16}}>
      <div className="bf-card bf-card-body"><div className="bf-muted" style={{fontSize:10}}>VEHICLES</div><div className="bf-kpi-value"><Truck size={17}/> {usage.vehicles ?? vehicles.length}</div></div>
      <div className="bf-card bf-card-body"><div className="bf-muted" style={{fontSize:10}}>USERS</div><div className="bf-kpi-value"><UsersRound size={17}/> {usage.users ?? users.length}</div></div>
      <div className="bf-card bf-card-body"><div className="bf-muted" style={{fontSize:10}}>SITES</div><div className="bf-kpi-value"><Building2 size={17}/> {usage.sites ?? sites.length}</div></div>
    </div>
  </>;
}
