import React,{useMemo,useState} from 'react';
import {KeyRound,Plus,ShieldCheck,UserX,UserCheck,RefreshCcw} from 'lucide-react'; import PageHeader from '../components/PageHeader'; import DataTable from '../components/DataTable'; import Modal from '../components/Modal'; import PermissionMatrix from '../components/PermissionMatrix'; import PhotoField from '../components/PhotoField'; import {useClientPortal} from '../ClientPortalContext'; import {getFleetPack} from '../config/fleetPacks'; import {MODULE_CATALOG,defaultPermissionSet} from '../config/moduleCatalog';
const userBlank={full_name:'',email:'',mobile:'',employee_code:'',designation:'',department:'',role_name:'Viewer',site_ids:[],primary_site_id:'',temporary_password:'',force_password_change:true,status:'active'};
function defaultModules(keys){return Object.fromEntries(keys.map(k=>[k,defaultPermissionSet(true)]));}
export default function UsersPage(){
 const {company,data,sites,demo,mutateDemo,apiAction,refresh,currentUser,userAccess}=useClientPortal(); const [createOpen,setCreateOpen]=useState(false);const [accessUser,setAccessUser]=useState(null);const [form,setForm]=useState(userBlank);const [busy,setBusy]=useState(false);const pack=getFleetPack(company?.fleetPack);const allowedKeys=(userAccess?.companyModuleKeys||pack?.recommendedModules||MODULE_CATALOG.map(m=>m.key));
 const users=data?.users||[]; const selectedAccess=useMemo(()=>accessUser?{module_permissions:accessUser.module_permissions||defaultModules((accessUser.module_keys||allowedKeys).slice(0,10)),site_ids:accessUser.site_ids||[],role_name:accessUser.role_name||'Viewer'}:null,[accessUser,allowedKeys]); const [draftAccess,setDraftAccess]=useState(null);
 const openAccess=(u)=>{setAccessUser(u);setDraftAccess({module_permissions:u.module_permissions||defaultModules(u.module_keys||[]),site_ids:u.site_ids||[],role_name:u.role_name||'Viewer'});} ;
 const create=async()=>{setBusy(true);try{if(demo){mutateDemo('users',r=>[...r,{...form,id:`du-${Date.now()}`,site_names:sites.filter(s=>form.site_ids.includes(s.id)).map(s=>s.name),mfa_enabled:false}]);}else{await apiAction('create_user',form);await refresh()}setCreateOpen(false);setForm(userBlank)}finally{setBusy(false)}};
 const saveAccess=async()=>{if(!accessUser||!draftAccess)return;setBusy(true);try{if(demo){mutateDemo('users',rows=>rows.map(u=>u.id===accessUser.id?{...u,...draftAccess,module_keys:Object.entries(draftAccess.module_permissions).filter(([,v])=>v?.view).map(([k])=>k),site_names:sites.filter(s=>draftAccess.site_ids.includes(s.id)).map(s=>s.name)}:u));}else{await apiAction('save_user_access',{user_id:accessUser.id,...draftAccess});await refresh()}setAccessUser(null);setDraftAccess(null)}finally{setBusy(false)}};
 const statusAction=async(u,status)=>{if(demo){mutateDemo('users',rows=>rows.map(x=>x.id===u.id?{...x,status}:x));return;}await apiAction(status==='active'?'unblock_user':'block_user',{user_id:u.id});await refresh()};
 const resetPassword=async(u)=>{const p=window.prompt(`Temporary password for ${u.full_name || u.email}:`);if(!p)return;if(demo){window.alert('Demo: password reset simulated.');return;}await apiAction('reset_user_password',{user_id:u.id,temporary_password:p,force_password_change:true});window.alert('Password reset. Existing sessions revoked.');};
 return <><PageHeader title="Users & Roles" subtitle="Owner-controlled role, site and module access with checkbox-based permissions." actions={<button className="bf-btn bf-btn-primary" onClick={()=>setCreateOpen(true)}><Plus size={15}/> Add User</button>}/><div className="bf-card"><DataTable columns={[{key:'full_name',label:'User'},{key:'designation',label:'Designation'},{key:'role_name',label:'Role'},{key:'site_names',label:'Sites',render:v=>Array.isArray(v)?v.join(', '):'—'},{key:'mfa_enabled',label:'Authenticator',render:v=><span className={`bf-status ${v?'active':'pending'}`}>{v?'Enabled':'Not enabled'}</span>},{key:'status',label:'Status',render:v=><span className={`bf-status ${v}`}>{v}</span>},{key:'actions',label:'Actions',render:(_,u)=><div style={{display:'flex',gap:5,flexWrap:'wrap'}}><button className="bf-btn bf-btn-secondary" onClick={(e)=>{e.stopPropagation();openAccess(u)}}><ShieldCheck size={13}/> Access</button><button className="bf-btn bf-btn-ghost" onClick={(e)=>{e.stopPropagation();resetPassword(u)}}><KeyRound size={13}/></button>{u.status==='blocked'?<button className="bf-btn bf-btn-ghost" onClick={(e)=>{e.stopPropagation();statusAction(u,'active')}}><UserCheck size={13}/></button>:<button className="bf-btn bf-btn-danger" onClick={(e)=>{e.stopPropagation();statusAction(u,'blocked')}}><UserX size={13}/></button>}</div>}]} rows={users}/></div>
 <Modal open={createOpen} title="Add Company User" width="820px" onClose={()=>setCreateOpen(false)} footer={<><button className="bf-btn bf-btn-ghost" onClick={()=>setCreateOpen(false)}>Cancel</button><button className="bf-btn bf-btn-primary" disabled={busy||!form.full_name||!form.email||!form.temporary_password} onClick={create}>{busy?'Creating…':'Create User'}</button></>}><div className="bf-form-grid"><div className="bf-field full"><label>User Photo</label><PhotoField demo={demo} ownerType="user" ownerId="new" onUploaded={(url,result)=>setForm({...form,photo_url:url,photo_path:result?.path||form.photo_path||''})}/></div>{[['full_name','Full Name'],['employee_code','Employee Code'],['email','Email / Username'],['mobile','Mobile'],['designation','Designation'],['department','Department'],['temporary_password','Temporary Password']].map(([k,l])=><div className="bf-field" key={k}><label>{l}</label><input className="bf-input" type={k==='temporary_password'?'password':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="bf-field"><label>Role</label><select className="bf-select" value={form.role_name} onChange={e=>setForm({...form,role_name:e.target.value})}>{(pack?.roles||['Company Admin','Viewer']).filter(r=>r!=='Company Owner').map(r=><option key={r}>{r}</option>)}</select></div><div className="bf-field full"><label>Site Access</label><div className="bf-action-checks" style={{margin:0}}>{sites.map(s=><label key={s.id}><input type="checkbox" checked={form.site_ids.includes(s.id)} onChange={e=>setForm({...form,site_ids:e.target.checked?[...form.site_ids,s.id]:form.site_ids.filter(id=>id!==s.id)})}/>{s.name}</label>)}</div></div></div></Modal>
 <Modal open={!!accessUser} title={`Module & Site Access — ${accessUser?.full_name||''}`} width="980px" onClose={()=>{setAccessUser(null);setDraftAccess(null)}} footer={<><button className="bf-btn bf-btn-ghost" onClick={()=>{setAccessUser(null);setDraftAccess(null)}}>Cancel</button><button className="bf-btn bf-btn-secondary" onClick={()=>setDraftAccess(d=>({...d,module_permissions:defaultModules(allowedKeys)}))}><RefreshCcw size={13}/> Select Allowed</button><button className="bf-btn bf-btn-primary" disabled={busy} onClick={saveAccess}>{busy?'Applying…':'Apply Changes'}</button></>}>
   {draftAccess?<><div className="bf-section-title">Authorized Sites</div><div className="bf-action-checks" style={{margin:'0 0 16px'}}>{sites.map(s=><label key={s.id}><input type="checkbox" checked={draftAccess.site_ids.includes(s.id)} onChange={e=>setDraftAccess({...draftAccess,site_ids:e.target.checked?[...draftAccess.site_ids,s.id]:draftAccess.site_ids.filter(id=>id!==s.id)})}/>{s.name}</label>)}</div><div className="bf-section-title">Module & Action Permissions</div><PermissionMatrix allowedModuleKeys={allowedKeys} modules={draftAccess.module_permissions} onChange={(key,value)=>setDraftAccess({...draftAccess,module_permissions:{...draftAccess.module_permissions,[key]:value}})}/></>:null}
 </Modal></>;
}
