import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Eye, History, RefreshCcw, Save } from 'lucide-react';
import { getPlans, updatePlan } from '../../../services/developerSaasApi';
import { getPricingHistory } from '../../../services/developerPlatformRegistryApi';

const PERIODS = ['1', '3', '6', '12'];
const card = 'rounded-xl border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] shadow-[0_1px_2px_rgba(0,0,0,.04)]';
const input = 'h-10 w-full rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] px-3 text-[12px] text-[var(--bf-dev-text)] outline-none focus:border-[var(--bf-dev-primary)]';

function money(value, currency = 'INR') {
  const amount = Number(value || 0);
  try { return new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount); }
  catch { return `₹${amount.toLocaleString('en-IN')}`; }
}

function Button({ children, primary=false, icon: Icon, ...props }) {
  return <button type="button" {...props} className={`inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg border px-3 text-[11px] font-semibold transition disabled:opacity-50 ${primary?'border-[var(--bf-dev-primary)] bg-[var(--bf-dev-primary)] text-white':'border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] text-[var(--bf-dev-text-2)] hover:bg-[var(--bf-dev-surface-2)]'}`}>{Icon&&<Icon size={14}/>} {children}</button>;
}

export default function PricingManagementPage(){
  const [plans,setPlans]=useState([]),[drafts,setDrafts]=useState({}),[history,setHistory]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[message,setMessage]=useState({error:'',success:''}),[previewKey,setPreviewKey]=useState('');
  async function load(){ setLoading(true); setMessage({error:'',success:''}); const [p,h]=await Promise.all([getPlans(),getPricingHistory()]); if(p.ok&&Array.isArray(p.plans)){setPlans(p.plans);setDrafts(Object.fromEntries(p.plans.map(plan=>[plan.id,JSON.parse(JSON.stringify(plan))])));if(!previewKey&&p.plans[0])setPreviewKey(p.plans[0].plan_key);} else setMessage({error:p.code||'Unable to load plans.',success:''}); if(h.ok)setHistory(h.history||[]); setLoading(false); }
  useEffect(()=>{load();},[]);
  const preview=useMemo(()=>plans.find(p=>p.plan_key===previewKey)||plans[0]||null,[plans,previewKey]);
  const previewDraft=preview?drafts[preview.id]||preview:null;
  function editPrice(planId,period,value){setDrafts(current=>({...current,[planId]:{...current[planId],prices:{...(current[planId]?.prices||{}),[period]:value}}}));}
  async function publish(plan){const draft=drafts[plan.id];if(!draft)return;setSaving(plan.id);setMessage({error:'',success:''});const result=await updatePlan({planId:plan.id,expectedRevision:plan.revision,planKey:plan.plan_key,name:draft.name,tagline:draft.tagline,badge:draft.badge,status:draft.status,currency:draft.currency,displayOrder:Number(draft.display_order||0),prices:draft.prices,limits:draft.limits||{},entitlements:draft.entitlements||[]});if(result.ok){setMessage({error:'',success:`${draft.name} pricing published live. Public pricing API now reads this revision.`});await load();}else setMessage({error:result.status===409?'This plan changed in another session. Refresh and retry.':result.message||result.code||'Unable to publish pricing.',success:''});setSaving('');}
  return <div className="min-h-[calc(100dvh-var(--bf-header-height,66px))] bg-[var(--bf-dev-page-bg)] text-[var(--bf-dev-text)]">
    <section className="bg-[var(--bf-dev-primary)] px-5 pb-9 pt-6 text-white sm:px-7 lg:px-8"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><h1 className="text-[clamp(24px,2vw,31px)] font-semibold tracking-[-.025em]">Live Pricing</h1><p className="mt-1.5 max-w-4xl text-[13px] leading-5 text-white/80">Edit 1, 3, 6 and 12 month plan values from the Developer Dashboard. Publishing updates <code>developer_plans.prices</code>, which is the public pricing API source of truth.</p></div><Button icon={RefreshCcw} onClick={load} disabled={loading}>Refresh</Button></div></section>
    <main className="-mt-[22px] space-y-4 px-4 pb-8 sm:px-6 lg:px-8">
      {(message.error||message.success)&&<div className={`${card} p-3 text-[11px] ${message.error?'border-rose-500/25 text-rose-500':'border-emerald-500/25 text-emerald-500'}`}>{message.error||message.success}</div>}
      <div className="grid gap-4 2xl:grid-cols-[minmax(0,1fr)_380px]">
        <div className="grid gap-4 md:grid-cols-2">{plans.map(plan=>{const d=drafts[plan.id]||plan;return <section key={plan.id} className={`${card} p-4`}><div className="flex items-start justify-between gap-3"><div><div className="text-[15px] font-extrabold">{plan.name}</div><div className="mt-1 text-[9px] uppercase tracking-[.12em] text-[var(--bf-dev-text-3)]">{plan.plan_key} · revision {plan.revision}</div></div><span className="rounded-full border border-emerald-500/25 bg-emerald-500/10 px-2 py-1 text-[9px] font-bold uppercase text-emerald-500">{plan.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{PERIODS.map(period=><label key={period} className="block text-[10px] font-semibold text-[var(--bf-dev-text-2)]">{period} month{period==='1'?'':'s'}<div className="relative mt-1.5"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-[11px] text-[var(--bf-dev-text-3)]">₹</span><input className={`${input} pl-7`} type="number" min="0" step="1" value={d.prices?.[period]??''} onChange={e=>editPrice(plan.id,period,e.target.value)}/></div></label>)}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-[var(--bf-dev-border)] pt-4"><Button icon={Eye} onClick={()=>setPreviewKey(plan.plan_key)}>Preview</Button><Button primary icon={Save} disabled={saving===plan.id} onClick={()=>publish(plan)}>{saving===plan.id?'Publishing…':'Save & Publish Live'}</Button></div></section>})}</div>
        <aside className="space-y-4"><section className={`${card} p-4`}><div className="flex items-center gap-2 text-[12px] font-bold"><Eye size={15}/>Pricing Preview</div>{previewDraft?<><select className={`${input} mt-3`} value={previewKey} onChange={e=>setPreviewKey(e.target.value)}>{plans.map(p=><option key={p.plan_key} value={p.plan_key}>{p.name}</option>)}</select><div className="mt-4 rounded-xl border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface-2)] p-4"><div className="text-[17px] font-black">{previewDraft.name}</div><div className="mt-1 text-[10px] text-[var(--bf-dev-text-3)]">{previewDraft.tagline}</div><div className="mt-4 space-y-2">{PERIODS.map(period=><div key={period} className="flex items-center justify-between rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] px-3 py-2"><span className="text-[10px]">{period}M</span><b className="text-[12px]">{money(previewDraft.prices?.[period],previewDraft.currency)}</b></div>)}</div></div><div className="mt-3 flex items-start gap-2 rounded-lg border border-emerald-500/20 bg-emerald-500/10 p-3 text-[10px] text-emerald-500"><CheckCircle2 size={14} className="mt-.5 shrink-0"/>Save & Publish changes the live database value immediately. Public website consumption is completed in Part 04.</div></>:<div className="mt-3 text-[10px] text-[var(--bf-dev-text-3)]">No plan available.</div>}</section><section className={`${card} p-4`}><div className="flex items-center gap-2 text-[12px] font-bold"><History size={15}/>Pricing History</div><div className="mt-3 max-h-[360px] space-y-2 overflow-y-auto pr-1">{history.length?history.map(row=><div key={row.id} className="rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface-2)] p-3"><div className="text-[10px] font-bold">{row.action} · {row.entity_id}</div><div className="mt-1 text-[9px] text-[var(--bf-dev-text-3)]">{new Date(row.created_at).toLocaleString()}</div>{row.after_payload?.prices&&<div className="mt-2 text-[9px] text-[var(--bf-dev-text-2)]">{PERIODS.map(p=>`${p}M ₹${Number(row.after_payload.prices?.[p]||0).toLocaleString('en-IN')}`).join(' · ')}</div>}</div>):<div className="text-[10px] text-[var(--bf-dev-text-3)]">Pricing changes will appear here.</div>}</div></section></aside>
      </div>
    </main>
  </div>;
}
