import React,{useEffect,useMemo,useState}from'react';
import{Bell,KeyRound,Lock,MonitorSmartphone,RefreshCcw,Save,ShieldCheck,UserRound}from'lucide-react';
import{beginMfaEnrollment,disableMfa,getDeveloperAccount,getMfaStatus,revokeDeveloperSession,revokeOtherDeveloperSessions,updateDeveloperProfile,verifyMfaEnrollment}from'../../../services/developerAccountApi';

const card='rounded-xl border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] shadow-[0_1px_2px_rgba(0,0,0,.04)]';
const input='h-10 w-full rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] px-3 text-[12px] text-[var(--bf-dev-text)] outline-none focus:border-[var(--bf-dev-primary)]';
function Button({children,primary=false,danger=false,icon:Icon,...props}){return <button type="button" {...props} className={`inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg border px-3 text-[11px] font-semibold transition disabled:opacity-50 ${primary?'border-[var(--bf-dev-primary)] bg-[var(--bf-dev-primary)] text-white':danger?'border-rose-500/25 bg-rose-500/10 text-rose-500':'border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] text-[var(--bf-dev-text-2)]'}`}>{Icon&&<Icon size={14}/>} {children}</button>}
const tabs=[['profile','My Profile',UserRound],['security','My Security',ShieldCheck],['sessions','My Sessions',MonitorSmartphone],['notifications','Notifications',Bell],['preferences','Preferences',RefreshCcw]];
function maskIp(v){if(!v)return'—';const s=String(v);if(s.includes(':'))return`${s.slice(0,8)}…`;const p=s.split('.');return p.length===4?`${p[0]}.${p[1]}.x.x`:'Protected';}
export default function DeveloperAccountPage(){
 const hash=(window.location.hash||'').replace('#','');const [tab,setTab]=useState(tabs.some(([k])=>k===hash)?hash:'profile');const[data,setData]=useState(null),[mfa,setMfa]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState({error:'',success:''}),[profile,setProfile]=useState({fullName:'',mobile:''}),[enroll,setEnroll]=useState(null),[code,setCode]=useState('');
 async function load(){setLoading(true);setMessage({error:'',success:''});const[a,m]=await Promise.all([getDeveloperAccount(),getMfaStatus()]);if(a.ok){setData(a);setProfile({fullName:a.profile?.full_name||'',mobile:a.profile?.mobile||''});}else setMessage({error:a.code||'Unable to load developer account.',success:''});if(m.ok)setMfa(m);setLoading(false)}
 useEffect(()=>{load()},[]);useEffect(()=>{window.history.replaceState(null,'',`${window.location.pathname}#${tab}`)},[tab]);
 const activeSessions=useMemo(()=>(data?.sessions||[]).filter(s=>s.status==='active'),[data]);
 async function saveProfile(){setSaving(true);const r=await updateDeveloperProfile(profile);if(r.ok){setMessage({error:'',success:'Profile updated successfully.'});await load()}else setMessage({error:r.code||'Unable to update profile.',success:''});setSaving(false)}
 async function begin(){const r=await beginMfaEnrollment();if(r.ok){setEnroll(r);setCode('');setMessage({error:'',success:'Authenticator setup started. Scan the QR code and enter the 6-digit code.'})}else setMessage({error:r.code||'Unable to start MFA enrollment.',success:''})}
 async function verify(){if(!enroll)return;setSaving(true);const r=await verifyMfaEnrollment(enroll.factorId,enroll.challengeId,code);if(r.ok){setMessage({error:'',success:'MFA enabled. A fresh sign-in is required.'});window.setTimeout(()=>window.location.replace('https://buddyfleets.in/login'),800)}else setMessage({error:r.code||'MFA verification failed.',success:''});setSaving(false)}
 async function disable(){const factor=mfa?.verifiedFactors?.[0];if(!factor)return;const otp=window.prompt('Enter your current 6-digit authenticator code to disable MFA.');if(!otp)return;const r=await disableMfa(factor.id,otp);if(r.ok){setMessage({error:'',success:'MFA disabled. A fresh sign-in is required.'});window.setTimeout(()=>window.location.replace('https://buddyfleets.in/login'),800)}else setMessage({error:r.code||'Unable to disable MFA.',success:''})}
 async function revokeOthers(){if(!window.confirm('Revoke every other active Buddy Fleets session for this account?'))return;const r=await revokeOtherDeveloperSessions();if(r.ok){setData(r);setMessage({error:'',success:'Other active sessions revoked.'})}else setMessage({error:r.code||'Unable to revoke sessions.',success:''})}
 async function revokeOne(id){const r=await revokeDeveloperSession(id);if(r.ok){setData(r);setMessage({error:'',success:'Session revoked.'})}else setMessage({error:r.code||'Unable to revoke session.',success:''})}
 return <div className="min-h-[calc(100dvh-var(--bf-header-height,66px))] bg-[var(--bf-dev-page-bg)] text-[var(--bf-dev-text)]"><section className="bg-[var(--bf-dev-primary)] px-5 pb-9 pt-6 text-white sm:px-7 lg:px-8"><h1 className="text-[clamp(24px,2vw,31px)] font-semibold">Developer Account</h1><p className="mt-1.5 text-[13px] text-white/80">Profile, MFA, active sessions and personal Developer CPanel preferences.</p></section><main className="-mt-[22px] grid gap-4 px-4 pb-8 sm:px-6 lg:grid-cols-[230px_minmax(0,1fr)] lg:px-8"><aside className={`${card} h-fit p-2`}>{tabs.map(([k,t,Icon])=><button key={k} onClick={()=>setTab(k)} className={`mb-1 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-[11px] font-semibold ${tab===k?'bg-[var(--bf-dev-primary)] text-white':'text-[var(--bf-dev-text-2)] hover:bg-[var(--bf-dev-surface-2)]'}`}><Icon size={14}/>{t}</button>)}</aside><section className="space-y-4">{(message.error||message.success)&&<div className={`${card} p-3 text-[11px] ${message.error?'border-rose-500/25 text-rose-500':'border-emerald-500/25 text-emerald-500'}`}>{message.error||message.success}</div>}{loading?<div className={`${card} p-8 text-center text-[12px] text-[var(--bf-dev-text-3)]`}>Loading secure account…</div>:<>
 {tab==='profile'&&<div className={`${card} p-4`}><div className="text-[13px] font-bold">My Profile</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-semibold text-[var(--bf-dev-text-2)]">Full name<input className={`${input} mt-1.5`} value={profile.fullName} onChange={e=>setProfile({...profile,fullName:e.target.value})}/></label><label className="text-[10px] font-semibold text-[var(--bf-dev-text-2)]">Email<input className={`${input} mt-1.5`} value={data?.profile?.email||''} disabled/></label><label className="text-[10px] font-semibold text-[var(--bf-dev-text-2)]">Mobile<input className={`${input} mt-1.5`} value={profile.mobile} onChange={e=>setProfile({...profile,mobile:e.target.value})}/></label><label className="text-[10px] font-semibold text-[var(--bf-dev-text-2)]">Portal role<input className={`${input} mt-1.5`} value="SUPER_ADMIN" disabled/></label></div><div className="mt-4 flex justify-end"><Button primary icon={Save} onClick={saveProfile} disabled={saving}>Save Profile</Button></div></div>}
 {tab==='security'&&<div className={`${card} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[13px] font-bold">Multi-Factor Authentication</div><div className="mt-1 text-[10px] text-[var(--bf-dev-text-3)]">Authenticator/TOTP backend is connected to the secure Buddy Fleets session architecture.</div></div><span className={`rounded-full border px-2 py-1 text-[9px] font-bold uppercase ${mfa?.mfaEnabled?'border-emerald-500/25 bg-emerald-500/10 text-emerald-500':'border-amber-500/25 bg-amber-500/10 text-amber-500'}`}>{mfa?.mfaEnabled?'Enabled':'Disabled'}</span></div>{!mfa?.mfaEnabled&&!enroll&&<div className="mt-4"><Button primary icon={KeyRound} onClick={begin}>Set up Authenticator</Button></div>}{enroll&&<div className="mt-4 grid gap-4 lg:grid-cols-[220px_1fr]"><div className="rounded-xl border border-[var(--bf-dev-border)] bg-white p-3">{enroll.qrCode?<img src={enroll.qrCode} alt="Buddy Fleets MFA QR" className="mx-auto aspect-square w-full object-contain"/>:<div className="p-6 text-center text-xs text-slate-500">QR unavailable</div>}</div><div><div className="text-[10px] font-bold">Manual setup key</div><div className="mt-1 break-all rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface-2)] p-3 font-mono text-[10px]">{enroll.secret||'—'}</div><label className="mt-3 block text-[10px] font-semibold">6-digit code<input className={`${input} mt-1.5 max-w-xs`} inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))}/></label><div className="mt-3"><Button primary icon={ShieldCheck} disabled={saving||code.length!==6} onClick={verify}>Verify & Enable MFA</Button></div></div></div>}{mfa?.mfaEnabled&&<div className="mt-4"><div className="rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface-2)] p-3 text-[10px]">Verified factor: <b>{mfa.verifiedFactors?.[0]?.friendlyName||'Authenticator'}</b></div><div className="mt-3"><Button danger icon={Lock} onClick={disable}>Disable MFA</Button></div></div>}</div>}
 {tab==='sessions'&&<div className={`${card} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[13px] font-bold">Active Sessions</div><div className="mt-1 text-[10px] text-[var(--bf-dev-text-3)]">Authenticated portal sessions are capped at 60 minutes. Short login flows and handoffs remain separate.</div></div><Button danger onClick={revokeOthers}>Revoke Other Sessions</Button></div><div className="mt-4 space-y-2">{activeSessions.map(s=><div key={s.id} className="flex flex-col gap-3 rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface-2)] p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="text-[10px] font-bold">{s.id===data.currentSessionId?'Current session':'Buddy Fleets session'} · {s.portal_type}</div><div className="mt-1 truncate text-[9px] text-[var(--bf-dev-text-3)]">IP {maskIp(s.ip_address)} · Last seen {s.last_seen_at?new Date(s.last_seen_at).toLocaleString():'—'} · Expires {s.http_session_expires_at?new Date(s.http_session_expires_at).toLocaleString():'—'}</div></div>{s.id!==data.currentSessionId&&<Button danger onClick={()=>revokeOne(s.id)}>Revoke</Button>}</div>)}</div></div>}
 {tab==='notifications'&&<div className={`${card} p-4`}><div className="text-[13px] font-bold">Notifications</div><p className="mt-2 text-[11px] leading-5 text-[var(--bf-dev-text-2)]">Header notifications, security notices and platform alerts share the Developer Dashboard notification center. Provider-level email/SMS/WhatsApp preferences are part of the final integration layer.</p></div>}
 {tab==='preferences'&&<div className={`${card} p-4`}><div className="text-[13px] font-bold">Preferences</div><p className="mt-2 text-[11px] leading-5 text-[var(--bf-dev-text-2)]">Theme, sidebar and navigation preferences remain controlled by the existing Buddy Fleets theme engine. Use the gear icon in the header for live Light/Dark, menu and layout customization.</p></div>}
 </>}</section></main></div>
}
