import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  ArrowLeft, Bell, Building2, CheckCircle2, Download, FileText, KeyRound,
  Lock, Plus, Printer, RefreshCcw, Save, ShieldCheck, Unlock, UserPlus, WalletCards,
} from 'lucide-react';
import { company360Action, getCompany360 } from '../../../services/developerCompany360Api';

const tabs = [
  ['overview','Overview'], ['profile','Company Profile'], ['subscription','Subscription'],
  ['billing','Billing & Payments'], ['invoices','Invoices'], ['employees','Employees & Access'],
  ['documents','Documents / KYC'], ['usage','Usage & Limits'], ['modules','Modules & Features'],
  ['overrides','Overrides'], ['portal','Portal Configuration'], ['communications','Communications'],
  ['security','Security'], ['activity','Activity Log'], ['support','Support & Notes'],
];
const card = 'rounded-xl border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface-2)] p-4';
const input = 'h-10 w-full rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] px-3 text-[11px] text-[var(--bf-dev-text)] outline-none focus:border-[var(--bf-dev-primary)]';
const label = 'block space-y-1 text-[10px] font-semibold text-[var(--bf-dev-text-2)]';

function Button({ children, icon: Icon, primary=false, danger=false, ...props }) {
  return <button type="button" {...props} className={`inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg border px-3 text-[11px] font-semibold transition disabled:opacity-50 ${primary?'border-[var(--bf-dev-primary)] bg-[var(--bf-dev-primary)] text-white':danger?'border-rose-500/30 bg-rose-500/10 text-rose-500':'border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] text-[var(--bf-dev-text-2)]'}`}>{Icon&&<Icon size={13}/>} {children}</button>;
}
function Stat({ title, value, sub }) { return <div className={card}><div className="text-[9px] uppercase tracking-[.12em] text-[var(--bf-dev-text-3)]">{title}</div><div className="mt-2 text-xl font-extrabold text-[var(--bf-dev-text)]">{value}</div>{sub&&<div className="mt-1 text-[9px] text-[var(--bf-dev-text-3)]">{sub}</div>}</div>; }
function Money({ value }) { return <>₹{Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2})}</>; }
function Empty({ text='No records yet.' }) { return <div className="rounded-lg border border-dashed border-[var(--bf-dev-border)] p-5 text-center text-[10px] text-[var(--bf-dev-text-3)]">{text}</div>; }

export default function Company360Page(){
  const { companyId } = useParams(); const navigate=useNavigate();
  const [data,setData]=useState(null), [loading,setLoading]=useState(true), [error,setError]=useState(''), [tab,setTab]=useState('overview'), [modal,setModal]=useState(null);
  async function load(){ setLoading(true); setError(''); const r=await getCompany360(companyId); if(r.ok)setData(r); else setError(r.status===401?'Developer session expired. Please sign in again.':'Unable to load Company 360 profile.'); setLoading(false); }
  useEffect(()=>{load();},[companyId]);
  const company=data?.company||{}, profile=data?.profile||{}, subscription=data?.subscription||{}, summary=data?.billingSummary||{};
  const activeEmployees=(data?.employees||[]).filter(e=>e.status==='active').length;
  async function act(payload, success){ const r=await company360Action(companyId,payload); if(!r.ok){alert(r.message||r.code||'Action failed');return false;} if(success)alert(success); await load(); setModal(null); return true; }

  function printCompany(){ window.print(); }
  async function exportExcel(){
    if(!data)return;
    const XLSX=await import('xlsx'); const wb=XLSX.utils.book_new();
    const add=(name,rows)=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.length?rows:[{Info:'No records'}]),name.slice(0,31));
    add('Company_Profile',[{...company,...profile}]); add('Subscription',[subscription]); add('Effective_Limits',[data.effective?.limits||{}]); add('Employees',data.employees||[]); add('Invoices',data.invoices||[]); add('Payments',data.payments||[]); add('Documents',data.documents||[]); add('Modules',(data.modules||[]).map(m=>({module_key:m.module_key,module_name:m.module_name,effective_access:m.effective_access,status:m.status}))); add('Announcements',data.announcements||[]); add('Notes',data.notes||[]);
    XLSX.writeFile(wb,`${(company.company_name||'Company').replace(/[^a-z0-9]+/gi,'_')}_BuddyFleets_Export.xlsx`);
  }
  if(loading)return <div className="p-8 text-sm text-[var(--bf-dev-text-3)]">Loading Company 360°...</div>;
  if(error||!data)return <div className="p-8"><Button icon={ArrowLeft} onClick={()=>navigate('/saas-platform/companies/all-companies')}>Back</Button><p className="mt-4 text-sm text-rose-500">{error||'Company not found.'}</p></div>;

  return <div className="space-y-4 print:bg-white">
    <div className={`${card} print:border-0 print:bg-white`}>
      <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
        <div className="min-w-0"><Button icon={ArrowLeft} onClick={()=>navigate('/saas-platform/companies/all-companies')}>All Companies</Button><div className="mt-4 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black text-[var(--bf-dev-text)]">{company.company_name}</h1><span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-1 text-[9px] font-bold uppercase text-emerald-500">{company.status?.replaceAll('_',' ')}</span></div><div className="mt-1 text-[10px] text-[var(--bf-dev-text-3)]">{company.company_code} · portal.buddyfleets.in/{company.subdomain_slug} · {profile.city||'—'}, {profile.state||'—'}</div><div className="mt-2 text-[10px] font-semibold text-[var(--bf-dev-primary)]">{data.effective?.plan?.name||data.effective?.planKey||'No plan assigned'}</div></div>
        <div className="flex flex-wrap gap-2 print:hidden"><Button icon={Printer} onClick={printCompany}>Print</Button><Button icon={Download} onClick={exportExcel}>Export Excel</Button><Button icon={Bell} onClick={()=>setModal('announcement')}>Send Announcement</Button><Button icon={WalletCards} onClick={()=>setModal('payment')}>Record Payment</Button><Button icon={UserPlus} primary onClick={()=>setModal('employee')}>Add Employee</Button></div>
      </div>
    </div>

    <div className="flex flex-wrap gap-2 rounded-xl border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface-2)] p-2 print:hidden">{tabs.map(([k,t])=><button key={k} onClick={()=>setTab(k)} className={`rounded-lg px-3 py-2 text-[10px] font-bold ${tab===k?'bg-[var(--bf-dev-primary)] text-white':'text-[var(--bf-dev-text-2)] hover:bg-[var(--bf-dev-surface)]'}`}>{t}</button>)}</div>

    <div className="print:hidden">
    {tab==='overview'&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Current Plan" value={data.effective?.plan?.name||'—'} sub={subscription.status||'No subscription'}/><Stat title="Total Invoiced" value={<Money value={summary.totalInvoiced}/>} /><Stat title="Total Paid" value={<Money value={summary.totalPaid}/>} /><Stat title="Outstanding" value={<Money value={summary.outstanding}/>} /></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Employees" value={activeEmployees} sub={`${data.employees.length} total`}/><Stat title="Vehicle Limit" value={data.effective?.limits?.vehicles_max??'Unlimited'}/><Stat title="User Limit" value={data.effective?.limits?.users??'Unlimited'}/><Stat title="Site Limit" value={data.effective?.limits?.sites??'Unlimited'}/></div><div className={card}><h3 className="text-[12px] font-bold text-[var(--bf-dev-text)]">Recent Company Activity</h3><p className="mt-2 text-[10px] text-[var(--bf-dev-text-3)]">Activity history is recorded server-side for company changes, employee access, billing and communications.</p></div></div>}

    {tab==='profile'&&<Section title="Company Profile"><Grid rows={[
      ['Company Name',company.company_name],['Company Code',company.company_code],['Legal Name',profile.legal_name],['Trade Name',profile.trade_name],['GSTIN',profile.gstin],['PAN',profile.pan],['CIN / Registration',profile.cin],['Aadhaar Ref',profile.aadhaar_last4?`•••• ${profile.aadhaar_last4}`:''],['Owner',profile.owner_name],['Owner Email',profile.owner_email],['Owner Mobile',profile.owner_mobile],['Company Email',profile.contact_email],['Company Mobile',profile.contact_mobile],['Billing Email',profile.billing_email],['Website',profile.website],['Address',[profile.address_line1,profile.address_line2,profile.city,profile.state,profile.postal_code,profile.country].filter(Boolean).join(', ')],
    ]}/></Section>}

    {tab==='subscription'&&<Section title="Subscription & Plan"><Grid rows={[["Status",subscription.status],["Current Plan",data.effective?.plan?.name||data.effective?.planKey],["Trial Start",subscription.trial_start_at],["Trial End",subscription.trial_end_at],["Subscription Start",subscription.subscription_start_at],["Subscription End",subscription.subscription_end_at]]}/></Section>}

    {tab==='billing'&&<Section title="Billing & Payments" action={<Button icon={Plus} primary onClick={()=>setModal('payment')}>Record Payment</Button>}><Table headers={['Date','Amount','Mode','Reference','Status']} rows={(data.payments||[]).map(p=>[p.payment_date,<Money value={p.amount}/>,p.payment_mode,p.transaction_reference,p.status])}/></Section>}

    {tab==='invoices'&&<Section title="Invoices & Receipts" action={<Button icon={Plus} primary onClick={()=>setModal('invoice')}>Generate Invoice</Button>}><Table headers={['Invoice','Date','Due','Amount','Paid','Status']} rows={(data.invoices||[]).map(i=>[i.invoice_number,i.invoice_date,i.due_date,<Money value={i.grand_total}/>,<Money value={i.paid_amount}/>,i.status])}/></Section>}

    {tab==='employees'&&<Section title="Employees & Access" action={<Button icon={UserPlus} primary onClick={()=>setModal('employee')}>Add Employee</Button>}><div className="space-y-2">{!data.employees.length&&<Empty/>}{data.employees.map(e=><div key={e.id} className="flex flex-col gap-3 rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] p-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="text-[11px] font-bold text-[var(--bf-dev-text)]">{e.full_name}</div><div className="mt-1 text-[9px] text-[var(--bf-dev-text-3)]">{e.email} · {e.role_key} · {e.branch||'No branch'} · {e.status}</div></div><div className="flex flex-wrap gap-2">{e.status==='blocked'?<Button icon={Unlock} onClick={()=>act({action:'unblock_employee',employeeId:e.id},'Employee access restored.')}>Unblock</Button>:<Button icon={Lock} danger onClick={()=>act({action:'block_employee',employeeId:e.id},'Employee blocked.')}>Block</Button>}<Button icon={KeyRound} onClick={()=>setModal({type:'reset',employee:e})}>Reset Password</Button></div></div>)}</div></Section>}

    {tab==='documents'&&<Section title="Documents / KYC"><Table headers={['Type','Document','Status','Expiry']} rows={(data.documents||[]).map(d=>[d.document_type,d.document_name,d.status,d.expiry_date])}/></Section>}
    {tab==='usage'&&<Section title="Usage & Limits"><Grid rows={[["Vehicles",`— / ${data.effective?.limits?.vehicles_max??'Unlimited'}`],["Employees",`${activeEmployees} / ${data.effective?.limits?.users??'Unlimited'}`],["Branches / Sites",`— / ${data.effective?.limits?.sites??'Unlimited'}`]]}/><p className="mt-3 text-[9px] text-[var(--bf-dev-text-3)]">Live usage counters will populate from transport module tables as those modules are connected.</p></Section>}
    {tab==='modules'&&<Section title="Modules & Features"><Table headers={['Module','Category','Effective Access','Availability UX']} rows={(data.modules||[]).map(m=>[m.module_name,m.category,m.effective_access,m.unavailable_behavior])}/></Section>}
    {tab==='overrides'&&<Section title="Company Overrides"><Grid rows={[["Override Enabled",data.override?.enabled?'Yes':'No'],["Override Plan",data.override?.plan_key||'Plan default'],["Vehicle Max",data.override?.limits_override?.vehicles_max??'Default'],["Users",data.override?.limits_override?.users??'Default'],["Sites",data.override?.limits_override?.sites??'Default'],["Module Overrides",(data.override?.entitlements_override||[]).join(', ')||'None']]}/></Section>}
    {tab==='portal'&&<Section title="Portal Configuration"><p className="text-[10px] text-[var(--bf-dev-text-3)]">Controls company dashboard widgets, sidebar visibility, landing screen and company-specific branding. Module visibility is resolved from Plan → Lifecycle Policy → Company Override → Employee Role.</p><div className="mt-4"><Grid rows={[["Landing Path",data.portalConfig?.landing_path||'/dashboard'],["Dashboard Widgets",Array.isArray(data.portalConfig?.dashboard_widgets)?data.portalConfig.dashboard_widgets.join(', '):'Default'],["Revision",data.portalConfig?.revision||1]]}/></div></Section>}
    {tab==='communications'&&<Section title="Communications" action={<Button icon={Bell} primary onClick={()=>setModal('announcement')}>Send Announcement</Button>}><Table headers={['Created','Title','Priority','Audience','Status']} rows={(data.announcements||[]).map(a=>[new Date(a.created_at).toLocaleString(),a.title,a.priority,a.audience_type,a.status])}/></Section>}
    {tab==='security'&&<Section title="Security"><Grid rows={[["Company Status",company.status],["Owner User ID",company.account_owner_user_id||'Not linked'],["Access Policy",company.status==='suspended'?'Blocked by company suspension':subscription.status||'Standard'],["Employees",`${activeEmployees} active`]]}/><p className="mt-3 text-[9px] text-[var(--bf-dev-text-3)]">Password hashes and session tokens are never shown. Block/unblock and password reset actions operate through secure server-side admin APIs.</p></Section>}
    {tab==='activity'&&<Section title="Activity Log"><p className="text-[10px] text-[var(--bf-dev-text-3)]">Company 360 actions are written to the existing Developer SaaS history/audit layer. A dedicated filtered timeline can be added without changing this architecture.</p></Section>}
    {tab==='support'&&<Section title="Support & Notes" action={<Button icon={Plus} onClick={()=>setModal('note')}>Add Note</Button>}><div className="space-y-2">{!data.notes.length&&<Empty/>}{data.notes.map(n=><div key={n.id} className="rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] p-3"><div className="text-[10px] font-bold text-[var(--bf-dev-text)]">{n.title||n.note_type}</div><div className="mt-1 whitespace-pre-wrap text-[10px] text-[var(--bf-dev-text-2)]">{n.body}</div></div>)}</div></Section>}

    </div>

    <div className="hidden print:block print:text-black">
      <div className="space-y-4">
        <h2 className="text-xl font-bold">Buddy Fleets — Company 360° Report</h2>
        <div>Generated: {new Date().toLocaleString()}</div>
        <Grid rows={[["Company",company.company_name],["Code",company.company_code],["Status",company.status],["Plan",data.effective?.plan?.name||data.effective?.planKey],["GSTIN",profile.gstin],["PAN",profile.pan],["Owner",profile.owner_name],["Owner Email",profile.owner_email],["Owner Mobile",profile.owner_mobile],["Address",[profile.address_line1,profile.address_line2,profile.city,profile.state,profile.postal_code].filter(Boolean).join(', ')]]}/>
        <Grid rows={[["Subscription Status",subscription.status],["Trial End",subscription.trial_end_at],["Subscription End",subscription.subscription_end_at],["Total Invoiced",`₹${Number(summary.totalInvoiced||0).toLocaleString('en-IN')}`],["Total Paid",`₹${Number(summary.totalPaid||0).toLocaleString('en-IN')}`],["Outstanding",`₹${Number(summary.outstanding||0).toLocaleString('en-IN')}`]]}/>
        <h3 className="font-bold">Employees</h3><Table headers={['Name','Email','Role','Branch','Status']} rows={(data.employees||[]).map(e=>[e.full_name,e.email,e.role_key,e.branch,e.status])}/>
        <h3 className="font-bold">Invoices</h3><Table headers={['Invoice','Date','Amount','Paid','Status']} rows={(data.invoices||[]).map(i=>[i.invoice_number,i.invoice_date,`₹${i.grand_total}`,`₹${i.paid_amount}`,i.status])}/>
        <h3 className="font-bold">Payments</h3><Table headers={['Date','Amount','Mode','Reference','Status']} rows={(data.payments||[]).map(p=>[p.payment_date,`₹${p.amount}`,p.payment_mode,p.transaction_reference,p.status])}/>
        <h3 className="font-bold">Modules</h3><Table headers={['Module','Access']} rows={(data.modules||[]).map(m=>[m.module_name,m.effective_access])}/>
      </div>
    </div>

    {modal&&<ModalShell title={typeof modal==='object'&&modal.type==='reset'?'Reset Employee Password':modal==='employee'?'Add Employee':modal==='payment'?'Record Payment':modal==='invoice'?'Generate Invoice':modal==='announcement'?'Send Company Announcement':'Add Internal Note'} onClose={()=>setModal(null)}>
      {modal==='employee'&&<EmployeeForm onSubmit={(p)=>act({action:'create_employee',...p},'Employee created successfully.')}/>} 
      {typeof modal==='object'&&modal.type==='reset'&&<ResetForm employee={modal.employee} onSubmit={(p)=>act({action:'reset_password',employeeId:modal.employee.id,...p},'Password reset successfully.')}/>} 
      {modal==='payment'&&<PaymentForm invoices={data.invoices||[]} onSubmit={(p)=>act({action:'record_payment',...p},'Payment recorded.')}/>} 
      {modal==='invoice'&&<InvoiceForm onSubmit={(p)=>act({action:'create_invoice',...p},'Invoice generated.')}/>} 
      {modal==='announcement'&&<AnnouncementForm onSubmit={(p)=>act({action:'send_announcement',...p},'Announcement published to company employees.')}/>} 
      {modal==='note'&&<NoteForm onSubmit={(p)=>act({action:'add_note',...p},'Note saved.')}/>} 
    </ModalShell>}
  </div>;
}

function Section({title,action,children}){return <div className={card}><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="text-[13px] font-bold text-[var(--bf-dev-text)]">{title}</h2><div className="print:hidden">{action}</div></div>{children}</div>}
function Grid({rows}){return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.map(([k,v])=><div key={k} className="rounded-lg border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface)] p-3"><div className="text-[9px] uppercase tracking-[.08em] text-[var(--bf-dev-text-3)]">{k}</div><div className="mt-1 break-words text-[11px] font-semibold text-[var(--bf-dev-text)]">{v||'—'}</div></div>)}</div>}
function Table({headers,rows}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr>{headers.map(h=><th key={h} className="border-b border-[var(--bf-dev-border)] px-3 py-2 text-[9px] uppercase text-[var(--bf-dev-text-3)]">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} className="border-b border-[var(--bf-dev-border)] px-3 py-2 text-[10px] text-[var(--bf-dev-text-2)]">{v||'—'}</td>)}</tr>)}</tbody></table></div>}
function ModalShell({title,onClose,children}){return <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/60 p-4 print:hidden"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-[var(--bf-dev-border)] bg-[var(--bf-dev-surface-2)] p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-black text-[var(--bf-dev-text)]">{title}</h3><Button onClick={onClose}>Close</Button></div>{children}</div></div>}
function Field({title,...props}){return <label className={label}>{title}<input {...props} className={input}/></label>}
function Select({title,children,...props}){return <label className={label}>{title}<select {...props} className={input}>{children}</select></label>}
function Submit({text='Save'}){return <div className="mt-4 flex justify-end"><button className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-[var(--bf-dev-primary)] px-4 text-[11px] font-bold text-white"><Save size={13}/>{text}</button></div>}
function EmployeeForm({onSubmit}){const[f,setF]=useState({fullName:'',email:'',mobile:'',employeeCode:'',designation:'',branch:'',roleKey:'viewer',password:'',forcePasswordChange:true});return <form onSubmit={e=>{e.preventDefault();onSubmit(f)}}><div className="grid gap-3 sm:grid-cols-2"><Field title="Full Name *" required value={f.fullName} onChange={e=>setF({...f,fullName:e.target.value})}/><Field title="Email *" type="email" required value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><Field title="Mobile" value={f.mobile} onChange={e=>setF({...f,mobile:e.target.value})}/><Field title="Employee ID" value={f.employeeCode} onChange={e=>setF({...f,employeeCode:e.target.value})}/><Field title="Designation" value={f.designation} onChange={e=>setF({...f,designation:e.target.value})}/><Field title="Branch" value={f.branch} onChange={e=>setF({...f,branch:e.target.value})}/><Select title="Role" value={f.roleKey} onChange={e=>setF({...f,roleKey:e.target.value})}><option value="owner">Company Owner</option><option value="admin">Company Admin</option><option value="fleet_manager">Fleet Manager</option><option value="dispatcher">Dispatcher</option><option value="accountant">Accountant</option><option value="operations_manager">Operations Manager</option><option value="driver_manager">Driver Manager</option><option value="viewer">Viewer</option></Select><Field title="Password *" type="password" minLength={8} required value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></div><label className="mt-3 flex items-center gap-2 text-[10px] text-[var(--bf-dev-text-2)]"><input type="checkbox" checked={f.forcePasswordChange} onChange={e=>setF({...f,forcePasswordChange:e.target.checked})}/>Force password change on first login</label><Submit text="Create Employee"/></form>}
function ResetForm({employee,onSubmit}){const[p,setP]=useState('');return <form onSubmit={e=>{e.preventDefault();onSubmit({password:p,forcePasswordChange:true})}}><p className="mb-3 text-[10px] text-[var(--bf-dev-text-3)]">Reset password for {employee.full_name}. Current password is never displayed.</p><Field title="New Password *" type="password" minLength={8} required value={p} onChange={e=>setP(e.target.value)}/><Submit text="Reset Password"/></form>}
function PaymentForm({invoices,onSubmit}){const[f,setF]=useState({invoiceId:'',amount:'',paymentDate:new Date().toISOString().slice(0,10),paymentMode:'bank_transfer',transactionReference:'',proofUrl:'',status:'submitted',remarks:''});return <form onSubmit={e=>{e.preventDefault();onSubmit(f)}}><div className="grid gap-3 sm:grid-cols-2"><Select title="Invoice" value={f.invoiceId} onChange={e=>setF({...f,invoiceId:e.target.value})}><option value="">Unallocated / Advance</option>{invoices.map(i=><option key={i.id} value={i.id}>{i.invoice_number} · ₹{i.grand_total}</option>)}</Select><Field title="Amount *" type="number" min="0" step="0.01" required value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><Field title="Payment Date *" type="date" required value={f.paymentDate} onChange={e=>setF({...f,paymentDate:e.target.value})}/><Select title="Mode" value={f.paymentMode} onChange={e=>setF({...f,paymentMode:e.target.value})}><option value="upi">UPI</option><option value="bank_transfer">Bank Transfer / NEFT / RTGS / IMPS</option><option value="card">Card</option><option value="payment_gateway">Payment Gateway</option><option value="cheque">Cheque</option><option value="cash">Cash</option><option value="other">Other</option></Select><Field title="Transaction / UTR" value={f.transactionReference} onChange={e=>setF({...f,transactionReference:e.target.value})}/><Field title="Payment Proof URL" value={f.proofUrl} onChange={e=>setF({...f,proofUrl:e.target.value})}/></div><Submit text="Record Payment"/></form>}
function InvoiceForm({onSubmit}){const[f,setF]=useState({invoiceType:'subscription',invoiceDate:new Date().toISOString().slice(0,10),dueDate:'',placeOfSupply:'Gujarat',interstate:false,items:[{description:'Buddy Fleets Subscription',quantity:1,rate:'',discount:0,taxRate:18,hsnSac:''}]});const item=f.items[0];return <form onSubmit={e=>{e.preventDefault();onSubmit(f)}}><div className="grid gap-3 sm:grid-cols-2"><Select title="Invoice Type" value={f.invoiceType} onChange={e=>setF({...f,invoiceType:e.target.value})}><option value="subscription">Subscription</option><option value="renewal">Renewal</option><option value="upgrade">Upgrade / Downgrade</option><option value="addon">Add-on</option><option value="custom">Custom</option><option value="proforma">Proforma</option></Select><Field title="Invoice Date" type="date" value={f.invoiceDate} onChange={e=>setF({...f,invoiceDate:e.target.value})}/><Field title="Due Date" type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/><Field title="Place of Supply" value={f.placeOfSupply} onChange={e=>setF({...f,placeOfSupply:e.target.value})}/><Field title="Description" value={item.description} onChange={e=>setF({...f,items:[{...item,description:e.target.value}]})}/><Field title="Rate" type="number" min="0" step="0.01" required value={item.rate} onChange={e=>setF({...f,items:[{...item,rate:e.target.value}]})}/><Field title="Discount" type="number" min="0" step="0.01" value={item.discount} onChange={e=>setF({...f,items:[{...item,discount:e.target.value}]})}/><Field title="Tax %" type="number" min="0" max="100" value={item.taxRate} onChange={e=>setF({...f,items:[{...item,taxRate:e.target.value}]})}/></div><label className="mt-3 flex items-center gap-2 text-[10px] text-[var(--bf-dev-text-2)]"><input type="checkbox" checked={f.interstate} onChange={e=>setF({...f,interstate:e.target.checked})}/>Inter-state supply (IGST)</label><Submit text="Generate Invoice"/></form>}
function AnnouncementForm({onSubmit}){const[f,setF]=useState({title:'',message:'',priority:'normal',requireAcknowledgement:true,allowDismiss:true});return <form onSubmit={e=>{e.preventDefault();onSubmit(f)}}><Field title="Title *" required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><label className={`${label} mt-3`}>Message *<textarea required rows={6} value={f.message} onChange={e=>setF({...f,message:e.target.value})} className={`${input} h-auto py-2`}/></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><Select title="Priority" value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option value="normal">Normal</option><option value="important">Important</option><option value="critical">Critical</option></Select><label className="flex items-end gap-2 pb-2 text-[10px] text-[var(--bf-dev-text-2)]"><input type="checkbox" checked={f.requireAcknowledgement} onChange={e=>setF({...f,requireAcknowledgement:e.target.checked})}/>Require acknowledgement</label></div><Submit text="Send to All Active Employees"/></form>}
function NoteForm({onSubmit}){const[f,setF]=useState({title:'',body:'',noteType:'internal'});return <form onSubmit={e=>{e.preventDefault();onSubmit(f)}}><Field title="Title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><label className={`${label} mt-3`}>Note *<textarea required rows={6} value={f.body} onChange={e=>setF({...f,body:e.target.value})} className={`${input} h-auto py-2`}/></label><Submit text="Save Note"/></form>}
